# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "clock",
    srcs = [
        "clock.go",
        "doc.go",
        "errors.go",
        "fake.go",
        "real.go",
    ],
    importpath = "go.mindclade.dev/libs/go/clock",
)

go_test(
    name = "clock_test",
    srcs = [
        "clock_test.go",
        "fake_test.go",
    ],
    embed = [":clock"],
)
