# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "testing",
    srcs = [
        "__init__.py",
        "compile.py",
        "devices.py",
        "goldens.py",
        "numerics.py",
        "performance.py",
    ],
    imports = ["../../.."],
    deps = [
        "//kernels/tilelang/autotune",
        "//kernels/tilelang/compiler",
        "@pypi//torch",
    ],
)
