#!/usr/bin/env python3
# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

"""Verify the checked-in Protobuf-ES projection is complete and pinned."""

from __future__ import annotations

import os
from pathlib import Path


def runfiles() -> Path:
    return Path(os.environ.get("RUNFILES_DIR") or os.environ.get("TEST_SRCDIR") or ".")


def main() -> int:
    root = runfiles()
    proto_files = sorted(
        path for path in root.rglob("*.proto") if "/protocols/proto/mindclade/" in path.as_posix()
    )
    generated_files = sorted(
        path
        for path in root.rglob("*_pb.ts")
        if "/sdk/typescript/src/generated/proto/mindclade/" in path.as_posix()
    )
    expected = {
        path.as_posix().split("/protocols/proto/", 1)[1].removesuffix(".proto") + "_pb.ts"
        for path in proto_files
    }
    actual = {
        path.as_posix().split("/sdk/typescript/src/generated/proto/", 1)[1]
        for path in generated_files
    }
    errors: list[str] = []
    if expected != actual:
        errors.append(
            f"generated TypeScript file set differs; missing={sorted(expected - actual)}, "
            f"extra={sorted(actual - expected)}"
        )
    marker = '@generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"'
    for path in generated_files:
        text = path.read_text(encoding="utf-8")
        if marker not in text:
            errors.append(f"{path}: generator identity differs")
        if "Scaffold" in text:
            errors.append(f"{path}: removed scaffold symbol remains")
    for error in errors:
        print(f"ERROR: {error}")
    if errors:
        return 1
    print(f"Protobuf-ES projection passed for {len(actual)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
