#!/usr/bin/env python3
# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

"""Verify the checked-in Protobuf-ES projection is complete and pinned."""

from __future__ import annotations

import datetime as dt
import json
import os
from pathlib import Path

WAIVER_FILE = "scaffold-removal-waiver.json"


def runfiles() -> Path:
    return Path(os.environ.get("RUNFILES_DIR") or os.environ.get("TEST_SRCDIR") or ".")


def load_scaffold_waiver(root: Path) -> tuple[str, set[str], list[str]]:
    errors: list[str] = []
    matches = sorted(path for path in root.rglob(WAIVER_FILE) if path.is_file())
    if len(matches) != 1:
        errors.append(f"expected one runfile named {WAIVER_FILE}, found {len(matches)}")
        return "Scaffold", set(), errors
    document = json.loads(matches[0].read_text(encoding="utf-8"))
    token = document.get("required_diagnostic_token", "Scaffold")
    expires_on = document.get("expires_on")
    if not isinstance(expires_on, str):
        errors.append(f"{matches[0]}: expires_on is required")
    else:
        expiry = dt.date.fromisoformat(expires_on)
        if expiry < dt.date.today():
            errors.append(f"{matches[0]}: waiver expired on {expires_on}")
    allowed = set(document.get("allowed_files", []))
    return token, allowed, errors


def main() -> int:
    root = runfiles()
    marker, scaffold_allowlist, errors = load_scaffold_waiver(root)
    proto_files = sorted(
        path for path in root.rglob("*.proto") if "/protocols/proto/mindclade/" in path.as_posix()
    )
    generated_files = sorted(
        path
        for path in root.rglob("*_pb.ts")
        if "/sdk/typescript/src/generated/proto/mindclade/" in path.as_posix()
    )
    expected = {
        path.as_posix().split("/protocols/proto/", 1)[1].removesuffix(".proto") + "_pb.ts"
        for path in proto_files
    }
    actual = {
        path.as_posix().split("/sdk/typescript/src/generated/proto/", 1)[1]
        for path in generated_files
    }
    if expected != actual:
        errors.append(
            f"generated TypeScript file set differs; missing={sorted(expected - actual)}, "
            f"extra={sorted(actual - expected)}"
        )
    generator_marker = (
        '@generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"'
    )
    for path in generated_files:
        text = path.read_text(encoding="utf-8")
        if generator_marker not in text:
            errors.append(f"{path}: generator identity differs")
        if marker in text:
            relative = path.as_posix().split("/sdk/typescript/src/generated/proto/", 1)[1]
            source = f"proto/{relative.removesuffix('_pb.ts')}.proto"
            if source not in scaffold_allowlist:
                errors.append(f"{path}: removed scaffold symbol remains")
        elif "Scaffold" in text:
            errors.append(f"{path}: removed scaffold symbol remains")
    for error in errors:
        print(f"ERROR: {error}")
    if errors:
        return 1
    print(f"Protobuf-ES projection passed for {len(actual)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
