#!/usr/bin/env python3
# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

"""Verify the checked-in Protobuf-ES projection is complete and pinned."""

from __future__ import annotations

import os
import re
from pathlib import Path

PACKAGE_PATTERN = re.compile(r"(?m)^\s*package\s+([A-Za-z][A-Za-z0-9_.]*)\s*;")
PROTO_SCAFFOLD_PATTERN = re.compile(r"(?m)^\s*message\s+([A-Za-z][A-Za-z0-9_]*Scaffold)\s*\{")
TYPESCRIPT_SCAFFOLD_PATTERN = re.compile(
    r'Message<"([A-Za-z][A-Za-z0-9_.]*\.[A-Za-z][A-Za-z0-9_]*Scaffold)">'
)


def runfiles() -> Path:
    return Path(os.environ.get("RUNFILES_DIR") or os.environ.get("TEST_SRCDIR") or ".")


def main() -> int:
    root = runfiles()
    proto_files = sorted(
        path for path in root.rglob("*.proto") if "/protocols/proto/mindclade/" in path.as_posix()
    )
    generated_files = sorted(
        path
        for path in root.rglob("*_pb.ts")
        if "/sdk/typescript/src/generated/proto/mindclade/" in path.as_posix()
    )
    expected_files = {
        path.as_posix().split("/protocols/proto/", 1)[1].removesuffix(".proto") + "_pb.ts"
        for path in proto_files
    }
    actual_files = {
        path.as_posix().split("/sdk/typescript/src/generated/proto/", 1)[1]
        for path in generated_files
    }
    errors: list[str] = []
    if expected_files != actual_files:
        errors.append(
            "generated TypeScript file set differs; "
            f"missing={sorted(expected_files - actual_files)}, "
            f"extra={sorted(actual_files - expected_files)}"
        )
    expected_scaffolds: dict[str, set[str]] = {}
    for path in proto_files:
        relative = path.as_posix().split("/protocols/proto/", 1)[1]
        target = relative.removesuffix(".proto") + "_pb.ts"
        text = path.read_text(encoding="utf-8")
        names = set(PROTO_SCAFFOLD_PATTERN.findall(text))
        if not names:
            expected_scaffolds[target] = set()
            continue
        package_match = PACKAGE_PATTERN.search(text)
        if package_match is None:
            errors.append(f"{path}: scaffold message declared without a protobuf package")
            expected_scaffolds[target] = set()
            continue
        package = package_match.group(1)
        expected_scaffolds[target] = {f"{package}.{name}" for name in names}

    generator_marker = (
        '@generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=js"'
    )
    for path in generated_files:
        relative = path.as_posix().split("/sdk/typescript/src/generated/proto/", 1)[1]
        text = path.read_text(encoding="utf-8")
        if generator_marker not in text:
            errors.append(f"{path}: generator identity differs")
        projected_scaffolds = set(TYPESCRIPT_SCAFFOLD_PATTERN.findall(text))
        source_scaffolds = expected_scaffolds.get(relative, set())
        if projected_scaffolds != source_scaffolds:
            errors.append(
                f"{path}: scaffold projection differs; "
                f"missing={sorted(source_scaffolds - projected_scaffolds)}, "
                f"extra={sorted(projected_scaffolds - source_scaffolds)}"
            )
    for error in errors:
        print(f"ERROR: {error}")
    if errors:
        return 1
    print(f"Protobuf-ES projection passed for {len(actual_files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
