# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")
package(default_visibility = ["//visibility:public"])

go_library(
    name = "reflection",
    srcs = ["doc.go", "handlers.go"],
    importpath = "go.mindclade.dev/libs/go/connectx/reflection",
    deps = ["//libs/go/connectx", "//libs/go/faults", "@com_connectrpc_connect//:connect", "@com_connectrpc_grpcreflect//:grpcreflect"],
)

go_test(name = "reflection_test", srcs = ["handlers_test.go"], embed = [":reflection"])
