# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "faults",
    srcs = [
        "classify.go",
        "code.go",
        "context.go",
        "doc.go",
        "fault.go",
        "fields.go",
        "options.go",
        "retry.go",
    ],
    importpath = "go.mindclade.dev/libs/go/faults",
)

go_test(
    name = "faults_test",
    srcs = [
        "classify_test.go",
        "code_test.go",
        "context_test.go",
        "fault_test.go",
        "fields_test.go",
        "retry_test.go",
    ],
    embed = [":faults"],
)
