# Copyright 2026 Mindclade. All rights reserved.
# Confidential and proprietary.

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "postgres",
    srcs = [
        "doc.go",
        "store.go",
    ],
    importpath = "mindclade.internal/libs/go/storage/lease/postgres",
    deps = [
        "//libs/go/faults",
        "//libs/go/storage/lease",
        "//libs/go/storage/sql/postgres",
    ],
)

go_test(
    name = "postgres_test",
    srcs = ["store_test.go"],
    embed = [":postgres"],
    deps = [
        "//libs/go/faults",
        "//libs/go/storage/lease",
        "//libs/go/storage/sql/sqltest",
    ],
)
