# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:private"])

filegroup(
    name = "scaffold_files",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)

go_library(
    name = "webhooks",
    srcs = [
        "delivery.go",
        "doc.go",
        "endpoint.go",
        "repository.go",
        "service.go",
        "signature.go",
        "subscription.go",
    ],
    importpath = "go.mindclade.dev/control/webhooks",
)
