# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

package(default_visibility = ["//visibility:private"])

sh_binary(
    name = "failure_injection",
    srcs = ["failure_injection.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "validate",
    srcs = ["validate.sh"],
    visibility = ["//visibility:public"],
)

exports_files(
    ["README.md"],
    visibility = ["//visibility:public"],
)
