# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

"""Go and Python must seal `inference-model-descriptor/v1` to the same bytes.

Go writes the descriptor and seals its digest; the Python worker recomputes that
digest before it will serve. If the two encoders drift, every worker rejects
every descriptor the control plane publishes — a total serving outage that no
single-language test can see. The fixture is generated by the Go writer and
checked in, so a change to either side has to update it deliberately.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
from pathlib import Path

from serving.contracts import CompatibilityClass, ModelDescriptor, ResourceEnvelope

FIXTURES = Path(__file__).resolve().parent / "fixtures"

MODEL_BUNDLE = "sha256:e8bebfc4f9adafe9b232c13f5547eef3bff0f2d3da3dbc6e98d94f69a6061eb4"
ENGINE_BUNDLE = "sha256:d1c4682583ee5ef93432f3c397a87c9921a2465e23f988a95be40a95cc3c89f8"
RESOLVED_CONFIG = "sha256:5ac6d48dedc51f671110b07a531e822128c91cdac44c249a677a45321f64955d"
KERNEL_MANIFEST = "sha256:5b5f5aa2ec370ac18b858b957721bdb22082199eb574e7b60d67648fdefbac3f"
SAFETY_POLICY = "sha256:fce8b57e76301846c42fad20317ea0c94b0ee37bf44d0c41ff15e319d37687b2"

CREATED = 1_800_000_000_000
EXPIRES = CREATED + 86_400_000


def descriptor(digest: str = "") -> ModelDescriptor:
    return ModelDescriptor(
        descriptor_digest=digest,
        model_id="model_019c0000000070008000000000000001",
        family="novafold",
        version="3.1.0",
        lifecycle="serving",
        model_bundle_digest=MODEL_BUNDLE,
        engine_bundle_digest=ENGINE_BUNDLE,
        resolved_config_digest=RESOLVED_CONFIG,
        kernel_manifest_digest=KERNEL_MANIFEST,
        safety_policy_digest=SAFETY_POLICY,
        capabilities=("msa", "structure", "templates"),
        compatibility_classes=(
            CompatibilityClass(
                class_id="forward-bf16-small",
                execution_kind="forward",
                precision="bf16",
                shape_bucket="tokens<=1024",
                maximum_batch_requests=8,
                maximum_batch_gpu_bytes=8 << 30,
                maximum_input_units=1024,
                maximum_output_units=512,
            ),
            CompatibilityClass(
                class_id="diffusion-fp16-large",
                execution_kind="diffusion_sample",
                precision="fp16",
                shape_bucket="atoms<=8192",
                maximum_batch_requests=2,
                maximum_batch_gpu_bytes=32 << 30,
                maximum_input_units=8192,
                maximum_output_units=4096,
            ),
        ),
        envelope=ResourceEnvelope(
            weights_resident_bytes=24 << 30,
            host_memory_bytes=32 << 30,
            gpu_memory_floor_bytes=40 << 30,
            gpu_memory_per_request_bytes=2 << 30,
            maximum_concurrent_requests=4,
            load_deadline_millis=120_000,
            drain_deadline_millis=30_000,
        ),
        accelerator_capability="sm90",
        minimum_runtime_version="1.4.0",
        schema_version=1,
        policy_epoch=12,
        created_unix_millis=CREATED,
        expires_unix_millis=EXPIRES,
    )


def test_python_reproduces_the_go_sealed_canonical_bytes() -> None:
    expected = (FIXTURES / "model_descriptor_v1.bin").read_bytes()
    assert descriptor().canonical_bytes() == expected


def test_python_seals_the_digest_the_go_writer_published() -> None:
    meta = json.loads((FIXTURES / "model_descriptor_v1.json").read_text())
    payload = (FIXTURES / "model_descriptor_v1.bin").read_bytes()
    assert "sha256:" + hashlib.sha256(payload).hexdigest() == meta["canonical_sha256"]
    sealed = dataclasses.replace(descriptor(), descriptor_digest=meta["descriptor_digest"])
    sealed.verify_digest()


def test_golden_descriptor_opens_with_the_declared_document_type() -> None:
    meta = json.loads((FIXTURES / "model_descriptor_v1.json").read_text())
    payload = (FIXTURES / "model_descriptor_v1.bin").read_bytes()
    assert payload.startswith(meta["document_type"].encode() + b"\n")
