# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "reflection",
    srcs = ["doc.go", "register.go"],
    importpath = "go.mindclade.dev/libs/go/grpcx/reflection",
    deps = [
        "//libs/go/faults",
        "@org_golang_google_grpc//reflection",
    ],
)

go_test(
    name = "reflection_test",
    srcs = ["register_test.go"],
    embed = [":reflection"],
    deps = [
        "//libs/go/faults",
        "@org_golang_google_grpc//:grpc",
    ],
)
