# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "ownerrefs",
    srcs = [
        "doc.go",
        "ownerrefs.go",
    ],
    importpath = "go.mindclade.dev/libs/go/kubernetes/ownerrefs",
    deps = [
        "//libs/go/faults",
        "@io_k8s_apimachinery//pkg/apis/meta/v1",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_sigs_controller_runtime//pkg/client",
        "@io_k8s_sigs_controller_runtime//pkg/controller/controllerutil",
    ],
)

go_test(
    name = "ownerrefs_test",
    srcs = ["ownerrefs_test.go"],
    embed = [":ownerrefs"],
    deps = [
        "@io_k8s_apimachinery//pkg/apis/meta/v1",
        "@io_k8s_apimachinery//pkg/runtime",
    ],
)
