# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "metadata",
    srcs = [
        "doc.go",
        "metadata.go",
    ],
    importpath = "go.mindclade.dev/libs/go/kubernetes/metadata",
    deps = [
        "//libs/go/faults",
        "//libs/go/requestmeta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/util/validation",
    ],
)

go_test(
    name = "metadata_test",
    srcs = ["metadata_test.go"],
    embed = [":metadata"],
    deps = [
        "//libs/go/faults",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
    ],
)
