# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "testing",
    srcs = [
        "__init__.py",
        "devices.py",
        "distributed.py",
        "fixtures.py",
        "numerics.py",
        "processes.py",
    ],
    data = ["py.typed"],
    imports = ["../../.."],
    deps = [
        "//libs/python/distributed",
        "//libs/python/errors",
        "@pypi//numpy",
    ],
)
