# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mindclade-system

resources:
  - ../../../kubernetes/base
  - ../../../kubernetes/policies

configMapGenerator:
  - name: mindclade-environment
    envs:
      - config.env

generatorOptions:
  labels:
    app.kubernetes.io/part-of: mindclade-platform
    mindclade.dev/owner: security-and-operations

labels:
  - includeSelectors: false
    pairs:
      mindclade.dev/environment: development

patches:
  - path: patch-resources.yaml
