# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../kubernetes/overlays/staging

configMapGenerator:
  - name: mindclade-environment
    namespace: mindclade-system
    envs:
      - config.env

generatorOptions:
  labels:
    app.kubernetes.io/part-of: mindclade-platform
    mindclade.dev/owner: security-and-operations

labels:
  - includeSelectors: false
    pairs:
      mindclade.dev/environment: staging
