# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "cache",
    srcs = [
        "doc.go",
        "entry.go",
        "errors.go",
        "internal.go",
        "key.go",
        "options.go",
        "store.go",
    ],
    importpath = "go.mindclade.dev/libs/go/storage/cache",
    deps = ["//libs/go/faults"],
)

go_test(
    name = "cache_test",
    srcs = ["contracts_test.go"],
    embed = [":cache"],
)
