# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("//tools/build:pytest.bzl", "pytest_test")

pytest_test(
    name = "test_fp8",
    srcs = ["test_fp8.py"],
    imports = ["../../../.."],
    deps = [
        "//kernels/ops/fp8",
        "@pypi//torch",
    ],
)
