# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "patch",
    srcs = [
        "doc.go",
        "patch.go",
    ],
    importpath = "go.mindclade.dev/libs/go/kubernetes/patch",
    deps = [
        "//libs/go/faults",
        "//libs/go/kubernetes",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_sigs_controller_runtime//pkg/client",
    ],
)

go_test(
    name = "patch_test",
    srcs = ["patch_test.go"],
    embed = [":patch"],
    deps = [
        "//libs/go/faults",
        "@io_k8s_apimachinery//pkg/api/errors",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_sigs_controller_runtime//pkg/client",
    ],
)
