# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

locals {
  labels = merge({
    managed-by = "terraform"
    owner      = var.owner
  }, var.labels)

  unknown_authorization_keys = toset(flatten([
    for certificate in values(var.certificates) :
    setsubtract(certificate.authorization_keys, toset(keys(var.dns_authorizations)))
  ]))

  uncovered_domains = toset(flatten([
    for certificate in values(var.certificates) : [
      for domain in certificate.domains : domain
      if !contains([
        for authorization_key in certificate.authorization_keys :
        try(var.dns_authorizations[authorization_key].domain, "")
      ], domain)
    ]
  ]))
}

resource "google_certificate_manager_dns_authorization" "this" {
  for_each = var.dns_authorizations

  project     = var.project_id
  location    = var.location
  name        = each.value.name
  domain      = each.value.domain
  type        = "PER_PROJECT_RECORD"
  description = coalesce(each.value.description, "Regional Gateway authorization for ${each.value.domain}.")
  labels      = local.labels

  deletion_policy = "PREVENT"

  lifecycle {
    prevent_destroy = true
  }
}

# The general DNS module intentionally rejects public CNAME records. These are the sole
# exception: each value is generated by Certificate Manager, scoped to one authorization, and
# cannot be confused with a public application endpoint.
resource "google_dns_record_set" "authorization" {
  for_each = var.dns_authorizations

  project      = var.dns_project_id
  managed_zone = each.value.managed_zone
  name         = google_certificate_manager_dns_authorization.this[each.key].dns_resource_record[0].name
  type         = google_certificate_manager_dns_authorization.this[each.key].dns_resource_record[0].type
  ttl          = each.value.ttl
  rrdatas      = [google_certificate_manager_dns_authorization.this[each.key].dns_resource_record[0].data]

  lifecycle {
    precondition {
      condition     = google_certificate_manager_dns_authorization.this[each.key].dns_resource_record[0].type == "CNAME"
      error_message = "Certificate Manager must generate a CNAME authorization record; refusing to write an unexpected public record type."
    }
  }
}

resource "google_certificate_manager_certificate" "this" {
  for_each = var.certificates

  project     = var.project_id
  location    = var.location
  name        = each.value.name
  description = coalesce(each.value.description, "Regional Google-managed Gateway certificate ${each.value.name}.")
  labels      = local.labels

  managed {
    domains = sort(tolist(each.value.domains))
    dns_authorizations = [
      for authorization_key in sort(tolist(each.value.authorization_keys)) :
      google_certificate_manager_dns_authorization.this[authorization_key].id
    ]
  }

  deletion_policy = "PREVENT"

  lifecycle {
    prevent_destroy = true

    precondition {
      condition     = length(local.unknown_authorization_keys) == 0
      error_message = "Every certificate authorization key must exist in dns_authorizations."
    }

    precondition {
      condition     = length(local.uncovered_domains) == 0
      error_message = "Every regional certificate SAN must have an exact matching DNS authorization domain."
    }
  }

  depends_on = [google_dns_record_set.authorization]
}
