# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

variable "project_id" {
  description = "Project that owns the regional Certificate Manager resources and their consuming Gateway."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{4,28}[a-z0-9]$", var.project_id))
    error_message = "project_id must be a valid Google Cloud project id."
  }
}

variable "location" {
  description = "Region shared by the certificates and their regional single-cluster Gateway."
  type        = string

  validation {
    condition     = var.location != "global" && can(regex("^[a-z]+(?:-[a-z0-9]+)+[0-9]$", var.location))
    error_message = "location must be a concrete Google Cloud region; this module does not create global certificates."
  }
}

variable "dns_project_id" {
  description = "Cloud DNS project that owns the already-created public managed zones."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{4,28}[a-z0-9]$", var.dns_project_id))
    error_message = "dns_project_id must be a valid Google Cloud project id."
  }
}

variable "dns_authorizations" {
  description = <<-EOT
    Regional per-project DNS authorizations keyed by a stable identifier. The module owns only
    the CNAME record generated by each authorization; the referenced public managed zone must
    already exist in dns_project_id and remains owned by its independent DNS state.
  EOT

  type = map(object({
    name         = string
    domain       = string
    managed_zone = string
    ttl          = optional(number, 300)
    description  = optional(string)
  }))

  validation {
    condition = length(var.dns_authorizations) > 0 && alltrue([
      for authorization in values(var.dns_authorizations) :
      can(regex("^[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?$", authorization.name)) &&
      can(regex("^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z]{2,63}$", authorization.domain)) &&
      can(regex("^[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?$", authorization.managed_zone)) &&
      authorization.ttl >= 30 && authorization.ttl <= 86400
    ])
    error_message = "Every DNS authorization requires an RFC1035 name, absolute domain without a trailing dot, managed-zone name, and TTL from 30 through 86400 seconds."
  }
}

variable "certificates" {
  description = <<-EOT
    Regional Google-managed certificates keyed by stable attachment identifier. Domain names
    are exact SANs: wildcard certificates are intentionally rejected. authorization_keys must
    reference dns_authorizations and provide one exact domain match for every SAN.
  EOT

  type = map(object({
    name               = string
    domains            = set(string)
    authorization_keys = set(string)
    description        = optional(string)
  }))

  validation {
    condition = length(var.certificates) > 0 && alltrue([
      for certificate in values(var.certificates) :
      can(regex("^[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?$", certificate.name)) &&
      length(certificate.domains) > 0 &&
      length(certificate.authorization_keys) > 0 &&
      alltrue([
        for domain in certificate.domains :
        !startswith(domain, "*.") &&
        can(regex("^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z]{2,63}$", domain))
      ])
    ])
    error_message = "Every certificate requires an RFC1035 name, one or more exact non-wildcard DNS SANs, and one or more authorization keys."
  }
}

variable "owner" {
  description = "Accountable team applied as a resource label."
  type        = string
  default     = "platform"
}

variable "labels" {
  description = "Additional labels merged over the module baseline."
  type        = map(string)
  default     = {}
}
