# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-gateway-proxy
  namespace: ai
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-gateway-proxy
