# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-gateway-proxy
  namespace: ai
  labels:
    app.kubernetes.io/name: ai-gateway-proxy
automountServiceAccountToken: false
