# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:private"])

go_library(
    name = "releases",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    importpath = "go.mindclade.dev/control/registry/releases",
    visibility = [
        "//control:__subpackages__",
        "//services:__subpackages__",
    ],
    deps = [
        "//control/artifacts",
        "//libs/go/faults",
        "//libs/go/identifiers",
    ],
)

go_test(
    name = "releases_test",
    srcs = glob(["*_test.go"]),
    embed = [":releases"],
)
