#!/usr/bin/env python3
# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

"""Static and connected Rust dependency supply-chain policy."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
UNSAFE_RE = re.compile(r"\bunsafe\b")


def cargo_packages() -> list[tuple[Path, dict]]:
    root = tomllib.loads((ROOT / "Cargo.toml").read_text())
    result = []
    for member in root.get("workspace", {}).get("members", []):
        manifest = ROOT / member / "Cargo.toml"
        if manifest.exists():
            result.append((manifest.parent, tomllib.loads(manifest.read_text())))
    return result


def dependency_tables(manifest: dict) -> list[dict]:
    tables = [
        manifest.get("dependencies", {}),
        manifest.get("dev-dependencies", {}),
        manifest.get("build-dependencies", {}),
    ]
    for target in manifest.get("target", {}).values():
        tables.extend(
            [
                target.get("dependencies", {}),
                target.get("dev-dependencies", {}),
                target.get("build-dependencies", {}),
            ]
        )
    return tables


def validate_dependency(
    name: str, value: object, directory: Path, manifest_path: Path
) -> list[str]:
    label = f"{manifest_path.relative_to(ROOT)}: {name}"
    if isinstance(value, str):
        return (
            []
            if value.startswith("=") and "*" not in value
            else [f"{label}: external dependency must be exactly pinned"]
        )
    if not isinstance(value, dict):
        return [f"{label}: dependency declaration is invalid"]
    if value.get("git"):
        return [f"{label}: git dependency is not admitted"]
    if value.get("workspace") is True:
        return []
    if path := value.get("path"):
        try:
            (directory / path).resolve().relative_to(ROOT)
        except OSError, ValueError:
            return [f"{label}: path dependency escapes the repository"]
        return []
    version = value.get("version")
    if not isinstance(version, str) or not version.startswith("=") or "*" in version:
        return [f"{label}: external dependency must be exactly pinned"]
    return []


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--connected", action="store_true")
    a = p.parse_args()
    workspace = tomllib.loads((ROOT / "Cargo.toml").read_text())
    deps = workspace.get("workspace", {}).get("dependencies", {})
    policy = tomllib.loads((ROOT / "security/rust-supply-chain.toml").read_text())
    allowed_unsafe = set(policy.get("unsafe", {}).get("allowed_first_party_crates", []))
    errors = []
    for name, value in deps.items():
        if isinstance(value, str):
            version = value
            git = None
        else:
            version = value.get("version", "")
            git = value.get("git")
        if git:
            errors.append(f"{name}: git dependency is not admitted")
        if "*" in version:
            errors.append(f"{name}: wildcard version is not admitted")
        if version and not version.startswith("="):
            errors.append(f"{name}: external workspace dependency must be exactly pinned")
    for directory, manifest in cargo_packages():
        manifest_path = directory / "Cargo.toml"
        for table in dependency_tables(manifest):
            for name, value in table.items():
                errors.extend(validate_dependency(name, value, directory, manifest_path))
        package = manifest.get("package", {}).get("name", "")
        unsafe_files = []
        for source in directory.glob("src/**/*.rs"):
            text = source.read_text(errors="replace")
            # Allow the literal policy lint itself; count executable unsafe usage/traits/impls.
            stripped = "\n".join(
                line
                for line in text.splitlines()
                if "#![forbid(unsafe_code)]" not in line and "#![deny(unsafe_code)]" not in line
            )
            if UNSAFE_RE.search(stripped):
                unsafe_files.append(source.relative_to(ROOT).as_posix())
        if unsafe_files:
            if package not in allowed_unsafe:
                errors.append(f"{package}: unsafe Rust is not admitted: {unsafe_files}")
            safety = directory / "SAFETY.md"
            if not safety.exists():
                errors.append(f"{package}: unsafe-admitted crate requires SAFETY.md")
    extra = allowed_unsafe - {m.get("package", {}).get("name", "") for _, m in cargo_packages()}
    for package in sorted(extra):
        errors.append(f"{package}: unsafe allowlist entry has no workspace crate")
    lock = ROOT / "Cargo.lock"
    lock_ready = (
        lock.exists()
        and lock.stat().st_size >= 128
        and "# This file is automatically @generated by Cargo." in lock.read_text(errors="replace")
    )
    if a.connected and not lock_ready:
        errors.append("Cargo.lock is not a committed Cargo-generated closure")
    if errors:
        print("\n".join(errors))
        return 1
    if a.connected:
        cargo_deny = shutil.which("cargo-deny")
        if not cargo_deny:
            print("cargo-deny is required for connected supply-chain qualification")
            return 1
        return subprocess.call(
            [cargo_deny, "check", "advisories", "bans", "licenses", "sources"], cwd=ROOT
        )
    print(
        "Rust static supply-chain policy passed"
        + (
            " with committed lock closure"
            if lock_ready
            else "; Cargo lock closure requires connected pinned-toolchain lane"
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
