---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: mindclade-system
  labels:
    app.kubernetes.io/part-of: mindclade-platform
    mindclade.dev/owner: security-and-operations
automountServiceAccountToken: false
