# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl","go_library","go_test")
package(default_visibility=["//visibility:public"])
go_library(name="credentials",srcs=["doc.go","tls.go"],importpath="go.mindclade.dev/libs/go/grpcx/credentials",deps=["@org_golang_google_grpc//credentials","//libs/go/faults"])
go_test(name="credentials_test",srcs=["tls_test.go"],embed=[":credentials"])
