# Copyright 2026 Mindclade. All rights reserved.
# Confidential, proprietary, and trade-secret information.

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "otel",
    srcs = ["doc.go", "otel.go"],
    importpath = "mindclade.internal/libs/go/httpx/otel",
    deps = [
        "//libs/go/faults",
        "//libs/go/httpx",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
    ],
)

go_test(
    name = "otel_test",
    srcs = ["otel_test.go"],
    embed = [":otel"],
    deps = ["//libs/go/faults"],
)
