# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

[package]
name="mindclade_bytes_io"
version.workspace=true
edition.workspace=true
publish=false
[dependencies]
mindclade_faults={path="../faults"}
[lints]
workspace=true
