# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

exports_files(["README.md"])

go_library(
    name = "workqueue",
    srcs = [
        "doc.go",
        "errors.go",
        "model.go",
        "store.go",
        "worker.go",
    ],
    importpath = "go.mindclade.dev/libs/go/coordination/workqueue",
    deps = [
        "//libs/go/clock",
        "//libs/go/coordination",
        "//libs/go/faults",
        "//libs/go/identifiers",
        "//libs/go/requestmeta",
        "//libs/go/retry",
        "//libs/go/servicekit",
    ],
)

go_test(
    name = "workqueue_test",
    srcs = ["worker_test.go"],
    deps = [
        ":workqueue",
        "//libs/go/coordination/workqueue/memory",
        "//libs/go/faults",
        "//libs/go/requestmeta",
    ],
)
