// Copyright © 2026 Mindclade, LLC. All Rights Reserved.
// Mindclade Proprietary and Confidential.
// SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

syntax = "proto3";

package mindclade.inference.v1;

import "mindclade/inference/v1/request.proto";
import "mindclade/inference/v1/response.proto";
import "mindclade/inference/v1/stream.proto";

message ServiceScaffold {
  option deprecated = true;
  string reserved = 1;
}

message PredictRequest {
  InferenceRequest request = 1;
}

message PredictResponse {
  InferenceResponse response = 1;
}

message StreamPredictRequest {
  InferenceRequest request = 1;
}

message StreamPredictResponse {
  InferenceStreamEvent event = 1;
}

service InferenceService {
  rpc Predict(PredictRequest) returns (PredictResponse);
  rpc StreamPredict(StreamPredictRequest) returns (stream StreamPredictResponse);
}
