# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

exports_files([
    "README.md",
    "migrations/000001_audit.up.sql",
    "migrations/000001_audit.down.sql",
])

go_library(
    name = "postgres",
    srcs = [
        "doc.go",
        "errors.go",
        "store.go",
    ],
    importpath = "go.mindclade.dev/libs/go/audit/postgres",
    deps = [
        "//libs/go/audit",
        "//libs/go/faults",
        "//libs/go/identifiers",
        "//libs/go/storage/sql/postgres",
        "//libs/go/storage/sql/transaction",
    ],
)

go_test(
    name = "postgres_test",
    srcs = ["store_test.go"],
    embed = [":postgres"],
    deps = [
        "//libs/go/audit",
        "//libs/go/identifiers",
        "//libs/go/storage/sql/sqltest",
    ],
)
