# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

"""Train through the concrete worker boundary and serve its published eager bundle."""

from __future__ import annotations

import hashlib
import time
from pathlib import Path
from threading import Event

import numpy as np
import pytest
import torch
from safetensors.torch import save as save_safetensors

# The canonical Python protobuf modules are generated by Bazel and deliberately are not
# vendored into the root uv environment.  Keep the portable uv suite useful without turning
# this into a false failure: Bazel supplies this module and therefore still executes the test.
pytest.importorskip(
    "mindclade.artifact.v1.checkpoint_pb2",
    reason="canonical Python protobuf modules are generated by the Bazel test target",
)

from libs.python.identifiers import Digest
from libs.python.serialization import canonical_json_bytes
from libs.python.worker_runtime import StageEnvelope, StageKind
from services.workers.training import (
    CONFIG_LOGICAL_KIND,
    CONFIG_MEDIA_TYPE,
    DATASET_LOGICAL_KIND,
    DATASET_MEDIA_TYPE,
    TRAINING_OPERATION,
    ReferenceAffineTrainingEngine,
    build_executor,
    load_reference_affine_export,
    reference_topology_digest,
)
from services.workers.training.qualification import (
    LocalCheckpointCommitter,
    LocalScratchArtifactIO,
    local_checkpoint_provenance,
)
from serving.model_worker.reference import (
    ReferenceEngine,
    ReferenceEngineConfig,
    ReferenceInput,
    ReferenceRequest,
)


def _digest(value: bytes) -> str:
    return "sha256:" + hashlib.sha256(value).hexdigest()


def _resource(kind: str, suffix: int) -> str:
    return f"{kind}_019c00000000700080000000000000{suffix:02x}"


def test_training_worker_bundle_matches_eager_serving_runtime(tmp_path: Path) -> None:
    artifacts = LocalScratchArtifactIO(tmp_path)
    config = artifacts.add_bytes(
        canonical_json_bytes(
            {
                "accumulation_steps": 1,
                "allow_replicated_world_size_change": False,
                "dtype": "float32",
                "engine": TRAINING_OPERATION,
                "gradient_clip_norm": "10",
                "initial_bias": "0.5",
                "initial_scale": "2",
                "learning_rate": "0.1",
                "maximum_input_elements": 1024,
                "maximum_optimizer_steps": 12,
                "microbatch_size": 5,
                "model": "reference-affine-v1",
                "model_operation": "reference.affine.v1",
                "optimizer_steps_per_execution": 12,
                "schema_version": 1,
                "seed": 23,
                "weight_decay": "0",
            }
        ),
        media_type=CONFIG_MEDIA_TYPE,
        logical_kind=CONFIG_LOGICAL_KIND,
    )
    samples = torch.tensor([[-2.0], [-1.0], [0.0], [1.0], [2.0]], dtype=torch.float32)
    dataset = artifacts.add_bytes(
        save_safetensors({"inputs": samples, "targets": (samples * 3.0) - 1.0}),
        media_type=DATASET_MEDIA_TYPE,
        logical_kind=DATASET_LOGICAL_KIND,
    )
    topology = reference_topology_digest(
        backend="gloo",
        device_type="cpu",
        world_size=1,
        local_world_size=1,
    )
    stage = StageEnvelope(
        stage_id=_resource("stage", 31),
        kind=StageKind.TRAINING,
        operation=TRAINING_OPERATION,
        inputs=(config, dataset),
        output_namespace="integration/training-serving",
        resolved_config_digest=config.digest.text,
        reference_snapshot_digest=None,
        attempt=1,
        fencing_token=31,
        deadline_unix_millis=time.time_ns() // 1_000_000 + 60_000,
        metadata={
            "backend": "gloo",
            "checkpoint_id": _resource("checkpoint", 32),
            "code_digest": Digest.of_text("integration-source").text,
            "compatibility_policy_digest": Digest.of_text("replicated-adamw-v1").text,
            "device_type": "cpu",
            "local_world_size": "1",
            "model_digest": Digest.of_text("reference-affine-v1").text,
            "run_id": _resource("run", 33),
            "runtime_image_digest": Digest.of_text("integration-runtime").text,
            "toolchain_digest": Digest.of_text("integration-toolchain").text,
            "topology_digest": topology,
            "world_size": "1",
        },
    )
    result = build_executor(
        ReferenceAffineTrainingEngine(
            artifacts,
            workspace_root=tmp_path,
            checkpoint_committer=LocalCheckpointCommitter(
                tmp_path,
                local_checkpoint_provenance(
                    model=b"reference-affine-v1",
                    source=b"integration-source",
                    toolchain=b"integration-toolchain",
                    environment=b"integration-runtime",
                    compatibility_policy=b"replicated-adamw-v1",
                ),
                artifacts,
            ),
        )
    ).execute(stage)
    bundle = artifacts.materialize_tree(result.outputs[2])

    input_root = tmp_path / "serving-input"
    output_root = tmp_path / "serving-output"
    input_root.mkdir()
    output_root.mkdir()
    parity_input = torch.tensor([[-3.0, 0.25, 4.0]], dtype=torch.float32)
    payload = parity_input.numpy().tobytes()
    input_path = (input_root / "input.f32").resolve()
    input_path.write_bytes(payload)
    deadline = time.time_ns() // 1_000_000 + 60_000
    serving = ReferenceEngine(
        ReferenceEngineConfig(
            model_bundle_root=bundle,
            expected_bundle_digest=result.outputs[2].digest.text,
            output_root=output_root.resolve(),
            allowed_input_roots=(input_root.resolve(),),
            device="cpu",
            chunk_elements=2,
            iterations=1,
        )
    )
    output = serving.execute(
        ReferenceRequest(
            request_id="training-worker-serving-parity",
            model_bundle_digest=result.outputs[2].digest.text,
            operation="reference.affine.v1",
            deadline_unix_millis=deadline,
            maximum_input_bytes=len(payload),
            maximum_output_bytes=len(payload),
            input=ReferenceInput(
                segment_id="parity-input",
                generation=1,
                path=input_path,
                offset_bytes=0,
                length_bytes=len(payload),
                element_type="f32",
                shape=tuple(parity_input.shape),
                content_digest=_digest(payload),
                lease_expires_unix_millis=deadline,
            ),
        ),
        Event(),
    )
    served = torch.from_numpy(np.frombuffer(output.path.read_bytes(), dtype=np.float32).copy())
    served = served.reshape(parity_input.shape)
    trained = load_reference_affine_export(bundle / "model.safetensors")
    with torch.inference_mode():
        eager = trained(parity_input)
    torch.testing.assert_close(served, eager, rtol=0.0, atol=0.0)
    assert output.content_digest == _digest(output.path.read_bytes())

    overbound = torch.zeros(1025, dtype=torch.float32).numpy().tobytes()
    overbound_path = (input_root / "overbound.f32").resolve()
    overbound_path.write_bytes(overbound)
    with pytest.raises(ValueError, match="bundle input budget"):
        serving.execute(
            ReferenceRequest(
                request_id="training-worker-serving-overbound",
                model_bundle_digest=result.outputs[2].digest.text,
                operation="reference.affine.v1",
                deadline_unix_millis=deadline,
                maximum_input_bytes=len(overbound),
                maximum_output_bytes=len(overbound),
                input=ReferenceInput(
                    segment_id="overbound-input",
                    generation=1,
                    path=overbound_path,
                    offset_bytes=0,
                    length_bytes=len(overbound),
                    element_type="f32",
                    shape=(1025,),
                    content_digest=_digest(overbound),
                    lease_expires_unix_millis=deadline,
                ),
            ),
            Event(),
        )
