// Copyright © 2026 Mindclade, LLC. All Rights Reserved.
// Mindclade Proprietary and Confidential.
// SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

package consumers_test

import (
	"testing"

	"google.golang.org/protobuf/proto"

	artifactv1 "go.mindclade.dev/protocols/gen/go/mindclade/artifact/v1"
	commonv1 "go.mindclade.dev/protocols/gen/go/mindclade/common/v1"
	datav1 "go.mindclade.dev/protocols/gen/go/mindclade/data/v1"
	evaluationv1 "go.mindclade.dev/protocols/gen/go/mindclade/evaluation/v1"
	eventsv1 "go.mindclade.dev/protocols/gen/go/mindclade/events/v1"
	inferencev1 "go.mindclade.dev/protocols/gen/go/mindclade/inference/v1"
	orchestrationv1 "go.mindclade.dev/protocols/gen/go/mindclade/orchestration/v1"
	registryv1 "go.mindclade.dev/protocols/gen/go/mindclade/registry/v1"
	runtimev1 "go.mindclade.dev/protocols/gen/go/mindclade/runtime/v1"
	trainingv1 "go.mindclade.dev/protocols/gen/go/mindclade/training/v1"
)

// TestGeneratedGoSurface proves every promoted package is generated by Bazel,
// linkable in one consumer, and registered with its canonical fully-qualified
// message name. It lives in an underscore-prefixed Bazel package because action
// outputs are the Go authority and are not checked into the source-only Go module;
// the Go module loader intentionally excludes underscore-prefixed directories.
func TestGeneratedGoSurface(t *testing.T) {
	messages := []proto.Message{
		&artifactv1.ArtifactManifest{},
		&commonv1.ResourceId{},
		&datav1.SourceSnapshot{},
		&evaluationv1.Evaluation{},
		&eventsv1.EventEnvelope{},
		&inferencev1.InferenceRequest{},
		&orchestrationv1.Workflow{},
		&registryv1.ModelBundle{},
		&runtimev1.ExecutionTicket{},
		&trainingv1.TrainingRunSpecification{},
	}
	for _, message := range messages {
		if name := proto.MessageName(message); name == "" {
			t.Fatalf("%T has no registered protobuf descriptor", message)
		}
	}
}
