# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("//tools/build:pytest.bzl", "pytest_test")

package(default_visibility = ["//visibility:private"])

pytest_test(
    name = "test_export",
    srcs = ["test_export.py"],
    imports = ["../../../.."],
    deps = [
        "//models/adapters/export",
        "@pypi//torch",
    ],
)
