// Copyright © 2026 Mindclade, LLC. All Rights Reserved.
// Mindclade Proprietary and Confidential.
// SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

syntax = "proto3";

package mindclade.data.v1;

import "mindclade/common/v1/identifiers.proto";
import "mindclade/common/v1/pagination.proto";
import "mindclade/data/v1/dataset.proto";

message ServiceScaffold {
  option deprecated = true;
  string reserved = 1;
}

message ListDatasetsRequest { mindclade.common.v1.PageRequest page = 1; }
message ListDatasetsResponse {
  repeated Dataset datasets = 1;
  mindclade.common.v1.PageResponse page = 2;
}
message GetDatasetRequest { mindclade.common.v1.ResourceId dataset_id = 1; }
message GetDatasetResponse { Dataset dataset = 1; }

service DatasetService {
  rpc ListDatasets(ListDatasetsRequest) returns (ListDatasetsResponse);
  rpc GetDataset(GetDatasetRequest) returns (GetDatasetResponse);
}
