# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "internal",
    srcs = ["transport.go"],
    importpath = "go.mindclade.dev/sdk/go/internal",
    visibility = ["//sdk/go:__subpackages__"],
)
