# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//services/control_plane:__subpackages__"])

go_library(
    name = "iapauth",
    srcs = ["iapauth.go"],
    importpath = "go.mindclade.dev/services/control_plane/internal/providers/iapauth",
    deps = [
        "//libs/go/auth",
        "//libs/go/clock",
        "//libs/go/faults",
        "//services/control_plane/internal/config",
        "@org_golang_google_api//idtoken",
    ],
)

go_test(
    name = "iapauth_test",
    srcs = ["iapauth_test.go"],
    embed = [":iapauth"],
    deps = [
        "//libs/go/auth",
        "//libs/go/clock",
        "//libs/go/faults",
        "@org_golang_google_api//idtoken",
    ],
)
