# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "artifact_ref_proto",
    srcs = ["artifact_ref.proto"],
    strip_import_prefix = "/protocols/proto",
)

filegroup(
    name = "cargo_checkpoint_proto_sources",
    srcs = ["artifact_ref.proto"],
    visibility = ["//protocols/rust:__pkg__"],
)

proto_library(
    name = "errors_proto",
    srcs = ["errors.proto"],
    strip_import_prefix = "/protocols/proto",
)

proto_library(
    name = "identifiers_proto",
    srcs = ["identifiers.proto"],
    strip_import_prefix = "/protocols/proto",
)

proto_library(
    name = "pagination_proto",
    srcs = ["pagination.proto"],
    strip_import_prefix = "/protocols/proto",
)

go_proto_library(
    name = "common_go_proto",
    importpath = "go.mindclade.dev/protocols/gen/go/mindclade/common/v1",
    protos = [
        ":artifact_ref_proto",
        ":errors_proto",
        ":identifiers_proto",
        ":pagination_proto",
    ],
)
