# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "artifact_ref_proto",
    srcs = ["artifact_ref.proto"],
    strip_import_prefix = "/protocols/proto",
)

filegroup(
    name = "scaffold_files",
    srcs = glob(
        ["*.proto"],
        exclude = ["artifact_ref.proto"],
    ),
    visibility = ["//visibility:public"],
)
