# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")
package(default_visibility = ["//visibility:public"])

go_library(
    name = "connecttest",
    srcs = ["doc.go", "recorder.go", "server.go"],
    importpath = "go.mindclade.dev/libs/go/connectx/connecttest",
    deps = ["@com_connectrpc_connect//:connect"],
)

go_test(name = "connecttest_test", srcs = [
        "recorder_test.go",
        "server_test.go",
    ], embed = [":connecttest"], deps = ["@com_connectrpc_connect//:connect"])
