# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

"""A lockfile freshness gate is only worth its runtime if some input makes it fail.

Every case below names one corruption and pins the message that reports it. The three that
reproduce live defects are marked as such: PR #141's `Cargo.lock` edit, the added workspace
member, and the bumped `go.mod` requirement. Each of those returned exit code 0 from `bazelw`
while the log said the build did not complete, which is why they are asserted here on the message
rather than anywhere on a process status.

The guard cases matter as much as the drift cases. An absent, unreadable, or unparseable lockfile
has no digests to compare, and the one outcome that must never follow from "there was nothing to
compare" is a pass -- that is the exact fail-open shape the falsifiability review found ten
instances of. So a missing lock, a truncated lock, an unknown `lockFileVersion`, an extension map
with no file inputs, and a malformed `go.sum` line are each asserted to be reported errors.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
ANALYSIS = ROOT / "tools/analysis"

if str(ANALYSIS) not in sys.path:
    sys.path.insert(0, str(ANALYSIS))


def load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


freshness = load("check_lockfile_freshness", ANALYSIS / "check_lockfile_freshness.py")

CRATE_EXTENSION = "@@rules_rust+//crate_universe:extensions.bzl%crate"

GO_MOD = """module go.mindclade.dev

go 1.26.0

require (
\tconnectrpc.com/connect v1.18.1 // a trailing comment must not confuse the parser
\tgithub.com/lib/pq v1.12.3
)

require github.com/prometheus/client_golang v1.23.2 // indirect
"""

GO_SUM = """connectrpc.com/connect v1.18.1 h1:aaa=
connectrpc.com/connect v1.18.1/go.mod h1:bbb=
github.com/lib/pq v1.12.3 h1:ccc=
github.com/lib/pq v1.12.3/go.mod h1:ddd=
github.com/prometheus/client_golang v1.23.2 h1:eee=
github.com/prometheus/client_golang v1.23.2/go.mod h1:fff=
"""


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _write(root: Path, relative: str, text: str) -> None:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _lock(recorded: list[str], *, version: int = 26) -> str:
    """A minimal `MODULE.bazel.lock` recording `recorded` as crate_universe inputs."""
    return json.dumps(
        {
            "lockFileVersion": version,
            "registryFileHashes": {},
            "selectedYankedVersions": {},
            "moduleExtensions": {
                CRATE_EXTENSION: {
                    "general": {
                        "bzlTransitiveDigest": "irrelevant",
                        "usagesDigest": "irrelevant",
                        "recordedInputs": recorded,
                        "generatedRepoSpecs": {},
                    }
                }
            },
            "facts": {},
        }
    )


@pytest.fixture
def tree(tmp_path: Path) -> Path:
    """A hermetic miniature of the repository: one member crate, both lockfiles, one Go module."""
    cargo_lock = "# This file is automatically @generated by Cargo.\nversion = 4\n"
    cargo_toml = '[workspace]\nresolver = "3"\nmembers = [\n    "libs/rust/faults",\n]\n'
    member = '[package]\nname = "mindclade_faults"\nversion = "0.0.0"\n'

    _write(tmp_path, "Cargo.lock", cargo_lock)
    _write(tmp_path, "Cargo.toml", cargo_toml)
    _write(tmp_path, "libs/rust/faults/Cargo.toml", member)
    _write(tmp_path, "go.mod", GO_MOD)
    _write(tmp_path, "go.sum", GO_SUM)
    _write(tmp_path, "sdk/go/go.mod", "module github.com/Mindclade/mindclade-go\n\ngo 1.23.2\n")
    _write(tmp_path, "sdk/go/go.sum", "")
    _write(
        tmp_path,
        "MODULE.bazel.lock",
        _lock(
            [
                "ENV:CARGO_BAZEL_REPIN \\0",
                "REPO_MAPPING:rules_rust+,bazel_skylib bazel_skylib+",
                f"FILE:@@//Cargo.lock {_digest(cargo_lock)}",
                f"FILE:@@//Cargo.toml {_digest(cargo_toml)}",
                f"FILE:@@//libs/rust/faults/Cargo.toml {_digest(member)}",
            ]
        ),
    )
    return tmp_path


def _errors(root: Path) -> str:
    return "\n".join(freshness.check(root))


def test_a_consistent_tree_passes(tree: Path) -> None:
    assert freshness.check(tree) == []


# --------------------------------------------------------------------------------------------
# The three live defect shapes.
# --------------------------------------------------------------------------------------------


def test_edited_cargo_lock_is_reported(tree: Path) -> None:
    """PR #141 exactly: Cargo.lock moves, MODULE.bazel.lock does not."""
    (tree / "Cargo.lock").write_text("# edited\nversion = 4\n", encoding="utf-8")
    errors = _errors(tree)
    assert "Cargo.lock: changed since MODULE.bazel.lock was generated" in errors
    # The failure message must carry the fix, or a red CI run tells the author nothing.
    assert freshness.BAZEL_REPIN_COMMAND in errors
    assert "mod deps --lockfile_mode=update" in freshness.BAZEL_REPIN_COMMAND


def test_edited_member_manifest_is_reported(tree: Path) -> None:
    """A dependency edge added to a member crate invalidates the same extension."""
    (tree / "libs/rust/faults/Cargo.toml").write_text(
        '[package]\nname = "mindclade_faults"\n\n[dependencies]\nserde = "=1.0.0"\n',
        encoding="utf-8",
    )
    assert "libs/rust/faults/Cargo.toml: changed since MODULE.bazel.lock" in _errors(tree)


def test_added_workspace_member_is_reported(tree: Path) -> None:
    """The shape a digest comparison cannot see: a manifest the lock never recorded."""
    _write(tree, "libs/rust/newcomer/Cargo.toml", '[package]\nname = "mindclade_newcomer"\n')
    (tree / "Cargo.toml").write_text(
        '[workspace]\nmembers = [\n    "libs/rust/faults",\n    "libs/rust/newcomer",\n]\n',
        encoding="utf-8",
    )
    assert "libs/rust/newcomer/Cargo.toml: not recorded as a crate_universe input" in _errors(tree)


def test_added_member_via_a_glob_is_reported(tree: Path) -> None:
    """A glob member adds a crate with nobody editing a roster, so it is checked too."""
    _write(tree, "libs/rust/newcomer/Cargo.toml", '[package]\nname = "mindclade_newcomer"\n')
    (tree / "Cargo.toml").write_text(
        '[workspace]\nmembers = [\n    "libs/rust/*",\n]\n', encoding="utf-8"
    )
    assert "libs/rust/newcomer/Cargo.toml: not recorded as a crate_universe input" in _errors(tree)


def test_bumped_go_requirement_without_go_sum_is_reported(tree: Path) -> None:
    (tree / "go.mod").write_text(
        GO_MOD.replace("connectrpc.com/connect v1.18.1", "connectrpc.com/connect v1.18.2"),
        encoding="utf-8",
    )
    errors = _errors(tree)
    assert "go.sum does not authenticate connectrpc.com/connect v1.18.2" in errors
    assert freshness.GO_TIDY_COMMAND in errors


def test_go_sum_missing_only_the_go_mod_hash_is_reported(tree: Path) -> None:
    """The zip hash alone is not authentication; the go.mod hash is the one always required."""
    (tree / "go.sum").write_text(
        GO_SUM.replace("github.com/lib/pq v1.12.3/go.mod h1:ddd=\n", ""), encoding="utf-8"
    )
    assert "go.sum does not authenticate github.com/lib/pq v1.12.3" in _errors(tree)


# --------------------------------------------------------------------------------------------
# Guards on the checker itself. None of these may pass.
# --------------------------------------------------------------------------------------------


def test_absent_lockfile_is_an_error_not_a_pass(tree: Path) -> None:
    (tree / "MODULE.bazel.lock").unlink()
    errors = _errors(tree)
    assert "MODULE.bazel.lock is missing" in errors
    assert freshness.BAZEL_REPIN_COMMAND in errors


def test_unparseable_lockfile_is_an_error_not_a_pass(tree: Path) -> None:
    (tree / "MODULE.bazel.lock").write_text('{"lockFileVersion": 26,', encoding="utf-8")
    assert "MODULE.bazel.lock is not valid JSON" in _errors(tree)


def test_unreadable_lockfile_is_an_error_not_a_pass(tree: Path) -> None:
    """A directory where the lock should be: `is_file` is false, so it reads as absent."""
    (tree / "MODULE.bazel.lock").unlink()
    (tree / "MODULE.bazel.lock").mkdir()
    assert "MODULE.bazel.lock is missing" in _errors(tree)


def test_undecodable_lockfile_is_an_error_not_a_pass(tree: Path) -> None:
    (tree / "MODULE.bazel.lock").write_bytes(b"\xff\xfe\x00binary")
    assert "MODULE.bazel.lock could not be read" in _errors(tree)


def test_an_unknown_lock_format_version_is_an_error_not_a_pass(tree: Path) -> None:
    """A layout this parser has not been read against verifies nothing, so it must not pass."""
    text = (tree / "MODULE.bazel.lock").read_text(encoding="utf-8")
    (tree / "MODULE.bazel.lock").write_text(
        text.replace('"lockFileVersion": 26', '"lockFileVersion": 99'), encoding="utf-8"
    )
    errors = _errors(tree)
    assert "lockFileVersion 99" in errors
    assert "KNOWN_LOCK_FILE_VERSIONS" in errors


def test_a_lockfile_recording_no_file_inputs_is_an_error_not_a_pass(tree: Path) -> None:
    """Verifying an empty set is how a gate prints PASS forever."""
    (tree / "MODULE.bazel.lock").write_text(_lock(["ENV:CARGO_BAZEL_REPIN \\0"]), encoding="utf-8")
    assert "records no main-repository file inputs" in _errors(tree)


def test_a_lockfile_without_the_crate_extension_is_an_error_not_a_pass(tree: Path) -> None:
    document = json.loads((tree / "MODULE.bazel.lock").read_text(encoding="utf-8"))
    document["moduleExtensions"]["@@rules_python+//python/uv:uv.bzl%uv"] = document[
        "moduleExtensions"
    ].pop(CRATE_EXTENSION)
    (tree / "MODULE.bazel.lock").write_text(json.dumps(document), encoding="utf-8")
    assert "records no //crate_universe:extensions.bzl%crate extension" in _errors(tree)


def test_a_malformed_recorded_inputs_block_is_an_error_not_a_pass(tree: Path) -> None:
    document = json.loads((tree / "MODULE.bazel.lock").read_text(encoding="utf-8"))
    document["moduleExtensions"][CRATE_EXTENSION]["general"]["recordedInputs"] = 17
    (tree / "MODULE.bazel.lock").write_text(json.dumps(document), encoding="utf-8")
    assert "malformed recordedInputs" in _errors(tree)


def test_a_recorded_input_that_left_the_tree_is_reported(tree: Path) -> None:
    (tree / "libs/rust/faults/Cargo.toml").unlink()
    assert "recorded as an input of" in _errors(tree)
    assert "absent from the tree" in _errors(tree)


def test_a_malformed_go_sum_line_is_an_error_not_a_pass(tree: Path) -> None:
    (tree / "go.sum").write_text(GO_SUM + "this line has too few fields\n", encoding="utf-8")
    assert "malformed go.sum line" in _errors(tree)


def test_an_absent_go_sum_with_requirements_is_reported(tree: Path) -> None:
    (tree / "go.sum").unlink()
    assert "go.sum is missing while go.mod requires 3 module(s)" in _errors(tree)


def test_an_absent_go_sum_with_no_requirements_is_fine(tree: Path) -> None:
    """sdk/go is exactly this shape today: no requires, an empty go.sum, nothing to authenticate."""
    (tree / "sdk/go/go.sum").unlink()
    assert freshness.check(tree) == []


def test_a_missing_go_mod_is_an_error_not_a_pass(tree: Path) -> None:
    (tree / "sdk/go/go.mod").unlink()
    assert "sdk/go/go.mod is missing" in _errors(tree)


def test_an_unclosed_require_block_is_an_error_not_a_pass(tree: Path) -> None:
    (tree / "go.mod").write_text("module m\n\nrequire (\n\tfoo v1.0.0\n", encoding="utf-8")
    assert "a require block is never closed" in _errors(tree)


def test_a_locally_replaced_module_needs_no_checksum(tree: Path) -> None:
    """A replacement pointing at a directory has no module zip, so demanding a hash would misfire."""
    (tree / "go.mod").write_text(
        GO_MOD + "\nreplace connectrpc.com/connect => ./vendor/connect\n", encoding="utf-8"
    )
    (tree / "go.sum").write_text(
        GO_SUM.replace("connectrpc.com/connect v1.18.1/go.mod h1:bbb=\n", ""), encoding="utf-8"
    )
    assert freshness.check(tree) == []


def test_a_replace_block_is_parsed_as_well_as_a_replace_line(tree: Path) -> None:
    (tree / "go.mod").write_text(
        GO_MOD + "\nreplace (\n\tconnectrpc.com/connect => ../connect\n)\n", encoding="utf-8"
    )
    (tree / "go.sum").write_text(
        GO_SUM.replace("connectrpc.com/connect v1.18.1/go.mod h1:bbb=\n", ""), encoding="utf-8"
    )
    assert freshness.check(tree) == []


# --------------------------------------------------------------------------------------------
# Wiring. A checker nobody runs is the eleventh instance of the defect.
# --------------------------------------------------------------------------------------------


def test_the_checker_is_registered_in_the_static_lane() -> None:
    runner = load("run_architecture_checks", ANALYSIS / "run_architecture_checks.py")
    assert ("lockfile freshness", freshness.check) in [
        (name, fn) for name, fn in runner.CHECKS if name == "lockfile freshness"
    ]


def test_the_real_repository_is_fresh() -> None:
    """The committed tree must satisfy its own gate; otherwise the branch is the defect."""
    assert freshness.check(ROOT) == []


def test_the_check_path_never_shells_out(tree: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """CI must never regenerate a lockfile. The check path therefore runs no subprocess at all.

    Asserted rather than assumed, because the failure it prevents is silent: a check that quietly
    repinned would turn the fail-closed `--lockfile_mode=error` contract into
    `--lockfile_mode=update` with extra steps, and the committed authority would become whatever
    resolution CI happened to reach.
    """

    def forbidden(*args: object, **kwargs: object) -> None:
        raise AssertionError("the check path must not run a subprocess")

    monkeypatch.setattr(freshness.subprocess, "run", forbidden)
    (tree / "Cargo.lock").write_text("# edited\n", encoding="utf-8")
    assert freshness.check(tree)
    assert freshness.main(["--root", str(tree)]) == 1


def test_fix_runs_the_sanctioned_command_and_re_checks(
    tree: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """`--fix` regenerates, then decides on the digests -- never on the command's exit status."""
    (tree / "Cargo.lock").write_text("# edited\n", encoding="utf-8")
    invoked: list[list[str]] = []

    class Result:
        # Exit code 0 from a command that repaired nothing: precisely the shape that let three
        # agents report a green Bazel run off the status line while the log said otherwise.
        returncode = 0

    def fake_run(argv: list[str], **kwargs: object) -> Result:
        invoked.append(argv)
        return Result()

    monkeypatch.setattr(freshness.subprocess, "run", fake_run)
    assert freshness.main(["--fix", "--root", str(tree)]) == 1
    assert invoked == [freshness.BAZEL_REPIN_COMMAND.split()]
    assert "mod deps" in " ".join(invoked[0])
    assert "did not resolve the drift" in capsys.readouterr().err


def test_fix_reports_success_only_when_the_digests_agree(
    tree: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    original = (tree / "Cargo.lock").read_text(encoding="utf-8")
    (tree / "Cargo.lock").write_text("# edited\n", encoding="utf-8")

    class Result:
        # The opposite trap: a non-zero status from a command that did in fact repair the tree.
        returncode = 3

    def fake_run(argv: list[str], **kwargs: object) -> Result:
        (tree / "Cargo.lock").write_text(original, encoding="utf-8")
        return Result()

    monkeypatch.setattr(freshness.subprocess, "run", fake_run)
    assert freshness.main(["--fix", "--root", str(tree)]) == 0


def test_fix_regenerates_nothing_when_the_tree_is_already_fresh(
    tree: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def forbidden(*args: object, **kwargs: object) -> None:
        raise AssertionError("--fix must not regenerate a lockfile that is already fresh")

    monkeypatch.setattr(freshness.subprocess, "run", forbidden)
    assert freshness.main(["--fix", "--root", str(tree)]) == 0


def test_the_checker_needs_no_third_party_import() -> None:
    """The static lane is stdlib-only; an added dependency would move this gate out of it."""
    source = (ANALYSIS / "check_lockfile_freshness.py").read_text(encoding="utf-8")
    imported = {
        line.split()[1].split(".")[0]
        for line in source.splitlines()
        if line.startswith("import ") or line.startswith("from ")
    }
    assert imported <= set(sys.stdlib_module_names) | {"__future__"}
