# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

"""Fail-closed admission event catalog and JSON payload validation."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, cast

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from configs.contract_validation import (  # noqa: E402
    load_json,
    validate,
    validate_schema_subset,
)


def load_json_yaml(path: Path) -> dict[str, Any]:
    """Load the repository's JSON-compatible YAML contract subset."""

    payload = "\n".join(
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if not line.startswith("#") and line.strip() != "---"
    ).strip()
    value = json.loads(payload)
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected one object")
    return value


def _objects(value: object) -> dict[str, Any]:
    return cast("dict[str, Any]", value) if isinstance(value, dict) else {}


def _items(value: object) -> list[Any]:
    return cast("list[Any]", value) if isinstance(value, list) else []


def build_asyncapi(catalog: dict[str, Any]) -> dict[str, Any]:
    """Build the deterministic AsyncAPI projection of the canonical catalog."""

    channels: dict[str, Any] = {}
    operations: dict[str, Any] = {}
    messages: dict[str, Any] = {}
    for raw_event in _items(catalog.get("events")):
        event = _objects(raw_event)
        channel = str(event.get("channel", ""))
        message = str(event.get("message", ""))
        channels[channel] = {
            "address": event.get("topic"),
            "messages": {message: {"$ref": f"#/components/messages/{message}"}},
        }
        operations[f"send{message}"] = {
            "action": "send",
            "channel": {"$ref": f"#/channels/{channel}"},
            "messages": [{"$ref": f"#/channels/{channel}/messages/{message}"}],
        }
        messages[message] = {
            "name": message,
            "title": event.get("title"),
            "summary": event.get("summary"),
            "contentType": event.get("content_type"),
            "headers": {
                "type": "object",
                "required": ["schema-version"],
                "properties": {"schema-version": {"type": "string", "const": "1"}},
                "additionalProperties": False,
            },
            "payload": {"$ref": f"./{event.get('schema', '')}"},
            "x-mindclade-delivery": event.get("delivery"),
            "x-mindclade-ordering": event.get("ordering"),
            "x-mindclade-partition-key": event.get("partition_key"),
            "x-mindclade-compatibility": event.get("compatibility"),
            "x-mindclade-sensitive-fields": event.get("sensitive_fields"),
        }
    return {
        "asyncapi": "3.0.0",
        "info": {
            "title": "Mindclade admission events",
            "version": "1.0.0",
            "description": (
                "Transactional-outbox contracts for AI-gateway reservation and policy state. "
                "Consumers must be idempotent because delivery is at least once."
            ),
        },
        "defaultContentType": catalog.get("default_content_type"),
        "channels": channels,
        "operations": operations,
        "components": {"messages": messages},
        "x-mindclade-generated-from": "protocols/events/catalog.yaml",
    }


def render_asyncapi(catalog: dict[str, Any]) -> str:
    header = (
        "# Copyright © 2026 Mindclade, LLC. All Rights Reserved.\n"
        "# Mindclade Proprietary and Confidential.\n"
        "# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary\n\n"
        "# Generated by tools/codegen/generate_event_catalog.py; do not edit.\n"
        "---\n"
    )
    return header + json.dumps(build_asyncapi(catalog), indent=2, ensure_ascii=False) + "\n"


def validate_contracts(root: Path) -> list[str]:
    errors: list[str] = []
    try:
        catalog_schema = load_json(root / "catalog.schema.json")
        catalog = load_json_yaml(root / "catalog.yaml")
        mapping_root = root.parent / "mappings"
        mapping_schema = load_json(mapping_root / "admission.schema.json")
        mapping = load_json_yaml(mapping_root / "admission.yaml")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return [str(exc)]

    for label, schema in (
        ("catalog.schema.json", catalog_schema),
        ("admission.schema.json", mapping_schema),
    ):
        errors.extend(f"{label}: {failure}" for failure in validate_schema_subset(schema))
    errors.extend(
        f"catalog.yaml {failure.path}: {failure.message}"
        for failure in validate(catalog, catalog_schema)
    )
    errors.extend(
        f"admission.yaml {failure.path}: {failure.message}"
        for failure in validate(mapping, mapping_schema)
    )

    raw_events = _items(catalog.get("events"))
    catalog_events = [_objects(item) for item in raw_events]
    topics = [str(event.get("topic", "")) for event in catalog_events]
    channels = [str(event.get("channel", "")) for event in catalog_events]
    messages = [str(event.get("message", "")) for event in catalog_events]
    if topics != sorted(topics) or len(set(topics)) != len(topics):
        errors.append("catalog events must be topic-sorted and topic-unique")
    if len(set(channels)) != len(channels):
        errors.append("catalog channels must be unique")
    if len(set(messages)) != len(messages):
        errors.append("catalog messages must be unique")

    schema_ids: set[str] = set()
    schema_root = (root / "schemas").resolve()
    for event in catalog_events:
        relative_schema = Path(str(event.get("schema", "")))
        schema_path = (root / relative_schema).resolve()
        if not schema_path.is_relative_to(schema_root):
            errors.append(f"{relative_schema}: schema escapes protocols/events/schemas")
            continue
        relative_fixture = relative_schema.relative_to("schemas")
        fixture_path = (
            root
            / "fixtures"
            / Path(str(relative_fixture).removesuffix(".schema.json") + ".valid.json")
        )
        try:
            schema = load_json(schema_path)
            fixture = load_json(fixture_path)
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            errors.append(str(exc))
            continue
        errors.extend(f"{relative_schema}: {failure}" for failure in validate_schema_subset(schema))
        if schema.get("$schema") != "https://json-schema.org/draft/2020-12/schema":
            errors.append(f"{relative_schema}: must use JSON Schema draft 2020-12")
        identifier = str(schema.get("$id", ""))
        if not identifier.startswith("https://schemas.mindclade.dev/events/"):
            errors.append(f"{relative_schema}: $id is not Mindclade event authority")
        if identifier in schema_ids:
            errors.append(f"{relative_schema}: duplicate $id {identifier!r}")
        schema_ids.add(identifier)
        if schema.get("type") != "object" or schema.get("additionalProperties") is not False:
            errors.append(f"{relative_schema}: event root must be a closed object")
        errors.extend(
            f"{fixture_path.relative_to(root)} {failure.path}: {failure.message}"
            for failure in validate(fixture, schema)
        )

    mapping_events = [_objects(item) for item in _items(mapping.get("events"))]
    mapped_topics = [str(event.get("topic", "")) for event in mapping_events]
    if mapped_topics != sorted(mapped_topics) or len(set(mapped_topics)) != len(mapped_topics):
        errors.append("admission event mappings must be topic-sorted and topic-unique")
    expected_mapping = {
        str(event.get("topic", "")): str(event.get("schema", "")) for event in catalog_events
    }
    actual_mapping = {
        str(event.get("topic", "")): str(event.get("payload_schema", ""))
        for event in mapping_events
    }
    if actual_mapping != expected_mapping:
        errors.append("admission event mapping does not exactly match the canonical catalog")

    expected_authority = sorted(
        f"protocols/events/{event.get('schema', '')}" for event in catalog_events
    )
    actual_authority = sorted(
        str(item) for item in _items(_objects(mapping.get("wire_authority")).get("events"))
    )
    if actual_authority != expected_authority:
        errors.append("admission mapping event authorities do not match catalog schemas")

    try:
        asyncapi = load_json_yaml(root / "asyncapi.yaml")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        errors.append(str(exc))
    else:
        if asyncapi != build_asyncapi(catalog):
            errors.append("asyncapi.yaml has generated drift from catalog.yaml")
    return sorted(set(errors))


def main() -> int:
    root = Path(__file__).resolve().parent
    errors = validate_contracts(root)
    for error in errors:
        print(f"ERROR: {error}")
    if errors:
        return 1
    print("admission event contract validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
