# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "httpxtest",
    srcs = [
        "doc.go",
        "problem.go",
        "server.go",
    ],
    importpath = "go.mindclade.dev/libs/go/httpx/httpxtest",
    deps = ["//libs/go/httpx"],
)

go_test(
    name = "httpxtest_test",
    srcs = [
        "problem_test.go",
        "server_test.go",
    ],
    embed = [":httpxtest"],
)
