# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//services/control_plane:__subpackages__"])

go_library(
    name = "eventing",
    srcs = ["eventing.go"],
    importpath = "go.mindclade.dev/services/control_plane/internal/foundation/eventing",
    deps = [
        "//libs/go/coordination/outbox",
        "//libs/go/messaging",
        "//libs/go/servicekit",
        "//libs/go/servicekit/production",
        "//services/control_plane/internal/foundation",
    ],
)
