#!/usr/bin/env python3
# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

"""The drift gate that makes `protocols/` the wire authority rather than a claim.

`protocols/` is documented as the source of truth for every cross-process contract, and
`.gitattributes` marks the artifacts emitted from it `linguist-generated=true` so they collapse
in review. Both statements were unenforced: nothing compared a committed artifact against what
its source would produce today, so a hand-edit of `sdk/typescript/src/generated/**` or an
un-regenerated `.proto` change would reach `main` reviewed by nobody — the generated files are
exactly the ones a reviewer is told to skip.

Two lanes, because the two useful properties have different costs.

`--mode regenerate` is the authority. It runs the real pinned generators into a temporary tree
and byte-compares against what is committed. It cannot be satisfied by anything except output
the generator actually produces, and it needs `node_modules` (`pnpm install --frozen-lockfile`).

`--mode static` is hermetic: standard library only, no subprocesses, no network, no
`node_modules`. `run_architecture_checks.py` calls `check()`, which is this lane, so drift fails
`pipeline.py --static-only` on every pull request. It cannot byte-compare, so instead it cross-
examines three independent witnesses to the same contract:

    W1  the `.proto` source           parsed from `protocols/proto/**`
    W2  the embedded file descriptor  the base64 `FileDescriptorProto` that protoc-gen-es bakes
                                      into `fileDesc("...")` in every `_pb.ts`
    W3  the emitted TypeScript        the `@generated from ...` annotations and the declarations
                                      and property names they sit above

W2 is the load-bearing one. It is a compiled artifact of the `.proto`, so it is the record of
what the generator actually saw, and it is not something anyone edits by hand to match a lie
told in W1 or W3. Editing a field name in a `_pb.ts` contradicts W2. Editing a `.proto` without
regenerating contradicts W2. Agreement across all three is what regeneration would produce.

DETERMINISM AND HERMETICITY. Byte comparison is only a gate if identical inputs give identical
bytes, so the two things that usually make such a gate flap are handled explicitly rather than
hoped about:

  * Absolute paths. Generation runs with `buf generate -o <tmp>`, which prefixes the output
    directory without entering the emitted content. Verified: a temp-tree generation is
    byte-identical to the committed tree, so no path normalization is needed and none is done —
    normalizing anyway would hide a real regression if a future plugin started embedding paths.
  * Timestamps. Neither protoc-gen-es nor openapi-typescript emits one. Nothing is stripped, for
    the same reason.
  * Tool versions. protoc-gen-es DOES stamp `@generated by protoc-gen-es v2.14.0` into every
    file. That is deliberately NOT normalized away: the version is pinned by `pnpm-lock.yaml`,
    so it is an input like any other, and a bump that is not accompanied by regenerated output
    is precisely the drift this gate exists to catch. The static lane checks the stamp against
    the pinned version in `package.json` for the same reason.
  * The proprietary licence header. It survives regeneration without any help from this tool:
    protoc-gen-es carries a `.proto` file's leading detached comments into its output, and every
    `.proto` here opens with the header. `check_license_headers.py` skips the generated tree
    (`SKIP_PREFIXES`), so the header is not re-inserted afterwards either. `api.ts` has no
    header because openapi-typescript has no equivalent behavior and its YAML source's comments
    are not carried; that asymmetry is generator behavior, not drift.
  * `clean: true` in `protocols/buf.gen.yaml`. Under `-o <tmp>` it cleans the temp prefix, so
    verification never mutates the working tree. This is the difference from
    `generate_typescript_sdk.py --check`, which regenerates in place and compares digests before
    and after — that leaves the tree rewritten whether it passes or fails.

COVERAGE IS ITSELF GATED. `GENERATED_RULES` below claims every `linguist-generated=true` pattern
in `.gitattributes` and states what this tool does about it. A new rule that nothing here claims
is an error, not a silent gap: the failure mode this whole file exists to prevent is a generated
artifact that no gate looks at, and the second one of those would otherwise arrive unannounced.

    python3 tools/codegen/verify_generated.py                  # static + regenerate
    python3 tools/codegen/verify_generated.py --mode static    # hermetic, what presubmit runs
    python3 tools/codegen/verify_generated.py --repeat         # also prove generation is stable
"""

from __future__ import annotations

import argparse
import base64
import binascii
import difflib
import json
import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

PROTO_ROOT = "protocols/proto"
TS_GENERATED_ROOT = "sdk/typescript/src/generated"
TS_PROTO_ROOT = f"{TS_GENERATED_ROOT}/proto"
TS_OPENAPI_FILE = f"{TS_GENERATED_ROOT}/api.ts"
OPENAPI_SOURCE = "protocols/openapi/public.openapi.yaml"
BUF_TEMPLATE = "protocols/buf.gen.yaml"
PROTOC_GEN_ES_PACKAGE = "@bufbuild/protoc-gen-es"
PROTOC_GEN_ES_PLUGIN = "protoc-gen-es"

# Bounded output. A first regeneration after a protocol change can differ in every file; a gate
# that prints all of it is a gate whose message nobody reads.
MAX_DIFF_FILES = 8
MAX_DIFF_LINES = 40

REGENERATED = "regenerated"
ABSENT = "absent"
UNVERIFIABLE = "unverifiable"


@dataclass(frozen=True)
class GeneratedRule:
    """One `linguist-generated=true` pattern and what this tool does about it."""

    pattern: str
    disposition: str
    reason: str


# Every `linguist-generated=true` pattern in `.gitattributes`, with its disposition. Checked
# against the file in both directions: an unclaimed pattern fails, and a claimed pattern that
# has disappeared from `.gitattributes` fails too — a generated tree that stops being declared
# generated is how one starts being reviewed as source, or stops being verified as output.
GENERATED_RULES: tuple[GeneratedRule, ...] = (
    GeneratedRule(
        f"{TS_GENERATED_ROOT}/**",
        REGENERATED,
        "protoc-gen-es and openapi-typescript output; regenerated and byte-compared",
    ),
    GeneratedRule(
        "protocols/**/*.pb.go",
        ABSENT,
        "Go bindings are produced by go_proto_library at build time and never committed",
    ),
    GeneratedRule(
        "protocols/**/*_pb2.py",
        ABSENT,
        "Python bindings are produced by py_proto_library at build time and never committed",
    ),
    GeneratedRule(
        "protocols/**/*_pb2.pyi",
        ABSENT,
        "Python stubs are produced by py_proto_library at build time and never committed",
    ),
    GeneratedRule(
        "protocols/**/*_connect.go",
        ABSENT,
        "Connect handlers are produced at build time and never committed",
    ),
    # Lockfiles resolve against remote registries. Regenerating one here would either need the
    # network — which this gate must not — or would compare a resolver's output against itself.
    # Each already has its own authority: `--lockfile_mode=error`, `cargo --locked`,
    # `uv run --frozen`, `pnpm install --frozen-lockfile`, `nix flake check --no-update-lock-file`.
    GeneratedRule("Cargo.lock", UNVERIFIABLE, "resolver output; gated by `cargo --locked`"),
    GeneratedRule("go.sum", UNVERIFIABLE, "resolver output; gated by the Go module verifier"),
    GeneratedRule(
        "pnpm-lock.yaml", UNVERIFIABLE, "resolver output; gated by `pnpm install --frozen-lockfile`"
    ),
    GeneratedRule("uv.lock", UNVERIFIABLE, "resolver output; gated by `uv run --frozen`"),
    GeneratedRule(
        "flake.lock",
        UNVERIFIABLE,
        "resolver output; gated by `nix flake check --no-update-lock-file`",
    ),
    GeneratedRule(
        "MODULE.bazel.lock", UNVERIFIABLE, "resolver output; gated by `--lockfile_mode=error`"
    ),
    # Vendored data with no in-repository generator. `check_blueprint_scaffold.py` reads it and
    # `tests/integration/test_blueprint_scaffold.py` ratchets it; there is nothing to regenerate.
    GeneratedRule(
        "docs/blueprint/production-monorepo-paths.txt",
        UNVERIFIABLE,
        "vendored manifest with no generator; gated by the blueprint scaffold checks",
    ),
)


class VerificationError(Exception):
    """A witness could not be read at all, which is a failure and never a skip."""


# ---------------------------------------------------------------------------------------
# Protobuf wire decoding
# ---------------------------------------------------------------------------------------
# Enough of the wire format to read a `FileDescriptorProto`, in the standard library, because
# the static lane must not acquire a `protobuf` dependency to run in `--static-only`. Field
# numbers below are from `descriptor.proto` and are part of protobuf's compatibility guarantee.

_WIRE_VARINT = 0
_WIRE_I64 = 1
_WIRE_LEN = 2
_WIRE_SGROUP = 3
_WIRE_EGROUP = 4
_WIRE_I32 = 5


def _read_varint(buf: bytes, pos: int) -> tuple[int, int]:
    result = 0
    shift = 0
    while True:
        if pos >= len(buf):
            raise VerificationError("truncated varint")
        if shift > 63:
            raise VerificationError("varint wider than 64 bits")
        byte = buf[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, pos
        shift += 7


def _iter_wire(buf: bytes) -> Iterator[tuple[int, bytes | int]]:
    """Yield `(field_number, value)` for one message; bytes for length-delimited, int otherwise."""
    pos = 0
    while pos < len(buf):
        tag, pos = _read_varint(buf, pos)
        number, wire = tag >> 3, tag & 0x7
        if number == 0:
            raise VerificationError("field number 0 is not valid")
        if wire == _WIRE_VARINT:
            value, pos = _read_varint(buf, pos)
            yield number, value
        elif wire == _WIRE_I64:
            yield number, int.from_bytes(buf[pos : pos + 8], "little")
            pos += 8
        elif wire == _WIRE_I32:
            yield number, int.from_bytes(buf[pos : pos + 4], "little")
            pos += 4
        elif wire == _WIRE_LEN:
            length, pos = _read_varint(buf, pos)
            end = pos + length
            if end > len(buf):
                raise VerificationError("length-delimited field runs past the end of the message")
            yield number, buf[pos:end]
            pos = end
        elif wire in (_WIRE_SGROUP, _WIRE_EGROUP):
            raise VerificationError("groups are not supported and proto3 cannot produce them")
        else:
            raise VerificationError(f"unknown wire type {wire}")


def _as_bytes(value: bytes | int, what: str) -> bytes:
    if not isinstance(value, bytes):
        raise VerificationError(f"expected a length-delimited {what}")
    return value


def _as_str(value: bytes | int, what: str) -> str:
    return _as_bytes(value, what).decode("utf-8")


def _as_int(value: bytes | int, what: str) -> int:
    if isinstance(value, bytes):
        raise VerificationError(f"expected a varint {what}")
    return value


# ---------------------------------------------------------------------------------------
# The shape the three witnesses are reduced to
# ---------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Member:
    """A message field or an enum value: a name and the number it is bound to."""

    name: str
    number: int

    def render(self) -> str:
        return f"{self.name}={self.number}"


@dataclass(frozen=True)
class Surface:
    """The declared contract of one `.proto` file, however it was witnessed.

    Deliberately names and numbers only. Types are left out because the three witnesses spell
    them differently — `.proto` writes `mindclade.common.v1.PageRequest`, the descriptor writes
    `.mindclade.common.v1.PageRequest`, TypeScript writes `PageRequest` — and reconciling three
    spellings is how a comparison acquires the special cases that eventually make it fail open.
    Names and numbers are the wire contract, spelled identically by all three.
    """

    package: str
    syntax: str
    messages: dict[str, tuple[Member, ...]]
    enums: dict[str, tuple[Member, ...]]
    services: dict[str, tuple[str, ...]]


def _empty_surface(package: str = "", syntax: str = "") -> Surface:
    return Surface(package=package, syntax=syntax, messages={}, enums={}, services={})


# ---------------------------------------------------------------------------------------
# W2 — the descriptor embedded in the generated TypeScript
# ---------------------------------------------------------------------------------------


def _decode_message_type(
    buf: bytes, prefix: str, enums: dict[str, tuple[Member, ...]]
) -> dict[str, tuple[Member, ...]]:
    """Flatten one `DescriptorProto` and its nesting into `{dotted name: fields}`.

    Nested enums are accumulated into `enums` under the same dotted naming, because a message
    that declares an enum inside itself is one declaration in the descriptor and two exported
    symbols in TypeScript.

    Map fields expand into a synthetic nested `XxxEntry` message carrying `options.map_entry`.
    protoc-gen-es does not emit a declaration for those, so counting them here would report a
    message missing from TypeScript on every `map<...>` field in the tree.
    """
    name = ""
    fields: list[Member] = []
    nested: list[bytes] = []
    nested_enums: list[bytes] = []
    is_map_entry = False
    for number, value in _iter_wire(buf):
        if number == 1:  # DescriptorProto.name
            name = _as_str(value, "message name")
        elif number == 2:  # DescriptorProto.field
            field_name = ""
            field_number = 0
            for fnum, fval in _iter_wire(_as_bytes(value, "field")):
                if fnum == 1:
                    field_name = _as_str(fval, "field name")
                elif fnum == 3:
                    field_number = _as_int(fval, "field number")
            fields.append(Member(field_name, field_number))
        elif number == 3:  # DescriptorProto.nested_type
            nested.append(_as_bytes(value, "nested type"))
        elif number == 4:  # DescriptorProto.enum_type
            nested_enums.append(_as_bytes(value, "nested enum type"))
        elif number == 7:  # DescriptorProto.options
            for onum, oval in _iter_wire(_as_bytes(value, "message options")):
                if onum == 7:  # MessageOptions.map_entry
                    is_map_entry = bool(_as_int(oval, "map_entry"))
    if not name:
        raise VerificationError("descriptor contains a message with no name")
    if is_map_entry:
        return {}
    dotted = f"{prefix}{name}"
    out: dict[str, tuple[Member, ...]] = {dotted: tuple(fields)}
    for child in nested_enums:
        enum_name, enum_values = _decode_enum_type(child, f"{dotted}.")
        enums[enum_name] = enum_values
    for child in nested:
        out.update(_decode_message_type(child, f"{dotted}.", enums))
    return out


def _decode_enum_type(buf: bytes, prefix: str) -> tuple[str, tuple[Member, ...]]:
    name = ""
    values: list[Member] = []
    for number, value in _iter_wire(buf):
        if number == 1:  # EnumDescriptorProto.name
            name = _as_str(value, "enum name")
        elif number == 2:  # EnumDescriptorProto.value
            value_name = ""
            value_number = 0
            for vnum, vval in _iter_wire(_as_bytes(value, "enum value")):
                if vnum == 1:
                    value_name = _as_str(vval, "enum value name")
                elif vnum == 2:
                    value_number = _as_int(vval, "enum value number")
            values.append(Member(value_name, value_number))
    if not name:
        raise VerificationError("descriptor contains an enum with no name")
    return f"{prefix}{name}", tuple(values)


def _decode_service(buf: bytes) -> tuple[str, tuple[str, ...]]:
    name = ""
    methods: list[str] = []
    for number, value in _iter_wire(buf):
        if number == 1:  # ServiceDescriptorProto.name
            name = _as_str(value, "service name")
        elif number == 2:  # ServiceDescriptorProto.method
            for mnum, mval in _iter_wire(_as_bytes(value, "method")):
                if mnum == 1:
                    methods.append(_as_str(mval, "method name"))
    if not name:
        raise VerificationError("descriptor contains a service with no name")
    return name, tuple(methods)


def decode_file_descriptor(blob: bytes) -> tuple[str, Surface]:
    """Return `(declared source file name, surface)` for a serialized `FileDescriptorProto`."""
    file_name = ""
    package = ""
    syntax = "proto2"  # descriptor.proto omits the field for proto2, which is its default
    messages: dict[str, tuple[Member, ...]] = {}
    enums: dict[str, tuple[Member, ...]] = {}
    services: dict[str, tuple[str, ...]] = {}
    for number, value in _iter_wire(blob):
        if number == 1:  # FileDescriptorProto.name
            file_name = _as_str(value, "file name")
        elif number == 2:  # FileDescriptorProto.package
            package = _as_str(value, "package")
        elif number == 4:  # FileDescriptorProto.message_type
            messages.update(_decode_message_type(_as_bytes(value, "message type"), "", enums))
        elif number == 5:  # FileDescriptorProto.enum_type
            enum_name, enum_values = _decode_enum_type(_as_bytes(value, "enum type"), "")
            enums[enum_name] = enum_values
        elif number == 6:  # FileDescriptorProto.service
            service_name, methods = _decode_service(_as_bytes(value, "service"))
            services[service_name] = methods
        elif number == 12:  # FileDescriptorProto.syntax
            syntax = _as_str(value, "syntax")
    return file_name, Surface(
        package=package, syntax=syntax, messages=messages, enums=enums, services=services
    )


# ---------------------------------------------------------------------------------------
# W1 — the `.proto` source
# ---------------------------------------------------------------------------------------

_PROTO_TOKEN = re.compile(
    r"""
    "(?:[^"\\\n]|\\.)*"        # string literal
  | '(?:[^'\\\n]|\\.)*'
  | \.?[A-Za-z_][A-Za-z0-9_.]* # identifier, possibly dotted or fully qualified
  | -?\d[\w.+-]*               # number, including hex and floats
  | [{}()\[\]<>,;=]            # punctuation the grammar depends on
  | \S                         # anything else, so an unknown character is a token and not silence
    """,
    re.VERBOSE,
)

_LINE_COMMENT = re.compile(r"//[^\n]*")
_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)

# Statements that declare nothing this gate compares, but are valid and must not be errors.
_PROTO_SKIPPED_STATEMENTS = frozenset({"option", "reserved", "extensions", "import"})
_PROTO_FIELD_LABELS = frozenset({"repeated", "optional", "required"})


class _ProtoParser:
    """A proto2/proto3 statement reader that extracts declared names and numbers.

    Fail-closed on purpose: an unrecognized statement raises rather than being skipped. A parser
    that shrugs at what it does not understand degrades into one that verifies a subset nobody
    can name, and the first `.proto` construct it silently drops is the first place drift can
    live. The cost is that a genuinely new construct requires an edit here, which is a bounded,
    visible cost with a message that says exactly what to add.
    """

    def __init__(self, text: str, relpath: str) -> None:
        stripped = _BLOCK_COMMENT.sub(" ", text)
        stripped = _LINE_COMMENT.sub(" ", stripped)
        self._tokens = _PROTO_TOKEN.findall(stripped)
        self._pos = 0
        self._relpath = relpath

    def _fail(self, message: str) -> VerificationError:
        near = " ".join(self._tokens[max(0, self._pos - 3) : self._pos + 3])
        return VerificationError(f"{self._relpath}: {message} (near: {near!r})")

    def _peek(self) -> str | None:
        return self._tokens[self._pos] if self._pos < len(self._tokens) else None

    def _next(self) -> str:
        token = self._peek()
        if token is None:
            raise self._fail("unexpected end of file")
        self._pos += 1
        return token

    def _expect(self, token: str) -> None:
        found = self._next()
        if found != token:
            raise self._fail(f"expected {token!r}, found {found!r}")

    def _skip_to_semicolon(self) -> None:
        """Consume a statement, following any brace/bracket groups it contains."""
        depth = 0
        while True:
            token = self._next()
            if token in "{[(":
                depth += 1
            elif token in "}])":
                depth -= 1
                if depth <= 0 and token == "}":
                    # An aggregate option body may end the statement without a semicolon.
                    if self._peek() == ";":
                        self._next()
                    return
            elif token == ";" and depth == 0:
                return

    def _skip_field_options(self) -> None:
        if self._peek() != "[":
            return
        depth = 0
        while True:
            token = self._next()
            if token == "[":
                depth += 1
            elif token == "]":
                depth -= 1
                if depth == 0:
                    return

    def _read_number(self) -> int:
        token = self._next()
        try:
            return int(token, 0)
        except ValueError as error:
            raise self._fail(f"expected a field number, found {token!r}") from error

    def parse(self) -> Surface:
        package = ""
        syntax = "proto2"
        messages: dict[str, tuple[Member, ...]] = {}
        enums: dict[str, tuple[Member, ...]] = {}
        services: dict[str, tuple[str, ...]] = {}
        while (token := self._peek()) is not None:
            self._next()
            if token == ";":
                continue
            if token in ("syntax", "edition"):
                self._expect("=")
                syntax = self._next().strip("\"'")
                self._expect(";")
            elif token == "package":
                package = self._next()
                self._expect(";")
            elif token in _PROTO_SKIPPED_STATEMENTS:
                self._skip_to_semicolon()
            elif token == "message":
                messages.update(self._parse_message("", enums))
            elif token == "enum":
                name, values = self._parse_enum("")
                enums[name] = values
            elif token == "service":
                name, methods = self._parse_service()
                services[name] = methods
            elif token == "extend":
                self._next()
                self._skip_to_semicolon()
            else:
                raise self._fail(f"unsupported top-level statement {token!r}")
        return Surface(
            package=package, syntax=syntax, messages=messages, enums=enums, services=services
        )

    def _parse_message(
        self, prefix: str, enums: dict[str, tuple[Member, ...]]
    ) -> dict[str, tuple[Member, ...]]:
        name = self._next()
        dotted = f"{prefix}{name}"
        self._expect("{")
        fields: list[Member] = []
        out: dict[str, tuple[Member, ...]] = {}
        while (token := self._next()) != "}":
            if token == ";":
                continue
            if token in _PROTO_SKIPPED_STATEMENTS:
                self._skip_to_semicolon()
            elif token == "message":
                out.update(self._parse_message(f"{dotted}.", enums))
            elif token == "enum":
                enum_name, values = self._parse_enum(f"{dotted}.")
                enums[enum_name] = values
            elif token == "extend":
                self._next()
                self._skip_to_semicolon()
            elif token == "oneof":
                self._next()
                self._expect("{")
                while (inner := self._next()) != "}":
                    if inner == ";":
                        continue
                    if inner == "option":
                        self._skip_to_semicolon()
                        continue
                    # Inside a oneof every member is `<type> <name> = <n>;`.
                    fields.append(self._parse_field_tail())
            elif token == "map":
                self._expect("<")
                while self._next() != ">":
                    continue
                fields.append(self._parse_field_tail())
            elif token == "group":
                raise self._fail("proto2 groups are not supported by this checker")
            elif token in _PROTO_FIELD_LABELS:
                self._next()  # the type
                fields.append(self._parse_field_tail())
            else:
                # `token` was the type; the name follows.
                fields.append(self._parse_field_tail())
        out[dotted] = tuple(fields)
        return out

    def _parse_field_tail(self) -> Member:
        """Read `<name> = <number> [options];`, with the type already consumed."""
        name = self._next()
        self._expect("=")
        number = self._read_number()
        self._skip_field_options()
        self._expect(";")
        return Member(name, number)

    def _parse_enum(self, prefix: str) -> tuple[str, tuple[Member, ...]]:
        name = self._next()
        self._expect("{")
        values: list[Member] = []
        while (token := self._next()) != "}":
            if token == ";":
                continue
            if token in _PROTO_SKIPPED_STATEMENTS:
                self._skip_to_semicolon()
                continue
            self._expect("=")
            number = self._read_number()
            self._skip_field_options()
            self._expect(";")
            values.append(Member(token, number))
        return f"{prefix}{name}", tuple(values)

    def _parse_service(self) -> tuple[str, tuple[str, ...]]:
        name = self._next()
        self._expect("{")
        methods: list[str] = []
        while (token := self._next()) != "}":
            if token == ";":
                continue
            if token in _PROTO_SKIPPED_STATEMENTS:
                self._skip_to_semicolon()
                continue
            if token != "rpc":
                raise self._fail(f"unsupported statement {token!r} inside a service")
            methods.append(self._next())
            # `( [stream] Type ) returns ( [stream] Type )` then either `;` or an options body.
            for _ in range(2):
                while self._next() != ")":
                    continue
            if self._peek() == "{":
                self._skip_to_semicolon()
            else:
                self._expect(";")
        return name, tuple(methods)


def parse_proto_source(text: str, relpath: str) -> Surface:
    return _ProtoParser(text, relpath).parse()


# ---------------------------------------------------------------------------------------
# W3 — the emitted TypeScript
# ---------------------------------------------------------------------------------------

_TS_HEADER = re.compile(
    r'^// @generated by protoc-gen-es v(?P<version>[\w.\-+]+) with parameter "(?P<parameter>[^"]*)"$',
    re.MULTILINE,
)
_TS_FILE_TAG = re.compile(
    r"^// @generated from file (?P<file>\S+) \(package (?P<package>[\w.]+), syntax (?P<syntax>\w+)\)$",
    re.MULTILINE,
)
_TS_FILE_DESC = re.compile(r'fileDesc\("(?P<blob>[A-Za-z0-9+/=_-]+)"')
_TS_MESSAGE = re.compile(r"^\s*\* @generated from message (?P<name>[\w.]+)$", re.MULTILINE)
_TS_ENUM = re.compile(r"^\s*\* @generated from enum (?P<name>[\w.]+)$", re.MULTILINE)
_TS_SERVICE = re.compile(r"^\s*\* @generated from service (?P<name>[\w.]+)$", re.MULTILINE)
_TS_FIELD = re.compile(
    r"^\s*\* @generated from field: .*?(?P<name>\w+) = (?P<number>\d+);$", re.MULTILINE
)
_TS_ENUM_VALUE = re.compile(
    r"^\s*\* @generated from enum value: (?P<name>\w+) = (?P<number>-?\d+);$", re.MULTILINE
)
_TS_RPC = re.compile(r"^\s*\* @generated from rpc (?P<name>[\w.]+)$", re.MULTILINE)

# Anchors that delimit the body a declaration's annotations belong to. Everything between one
# `@generated from message|enum|service` line and the next is that declaration's block.
_TS_BLOCK_ANCHOR = re.compile(
    r"^\s*\* @generated from (?:message|enum|service) [\w.]+$", re.MULTILINE
)


@dataclass(frozen=True)
class TypeScriptBinding:
    """What one `_pb.ts` says about itself, before any of it is believed."""

    relpath: str
    plugin_version: str
    plugin_parameter: str
    source_file: str
    surface: Surface
    descriptor_source_file: str
    descriptor_surface: Surface
    blocks: dict[str, str]


def _require(match: re.Match[str] | None, relpath: str, what: str) -> re.Match[str]:
    if match is None:
        raise VerificationError(
            f"{relpath}: no {what}; this file was not produced by the generator"
        )
    return match


def _split_blocks(text: str) -> dict[str, str]:
    """Map each declaration's fully qualified name to the source text that follows it."""
    anchors = list(_TS_BLOCK_ANCHOR.finditer(text))
    blocks: dict[str, str] = {}
    for index, anchor in enumerate(anchors):
        end = anchors[index + 1].start() if index + 1 < len(anchors) else len(text)
        name = anchor.group().rsplit(" ", 1)[1]
        blocks[name] = text[anchor.start() : end]
    return blocks


def read_typescript_binding(text: str, relpath: str) -> TypeScriptBinding:
    header = _require(_TS_HEADER.search(text), relpath, "protoc-gen-es provenance header")
    file_tag = _require(_TS_FILE_TAG.search(text), relpath, "`@generated from file` tag")
    file_desc = _require(_TS_FILE_DESC.search(text), relpath, "embedded `fileDesc(...)` descriptor")
    try:
        # protoc-gen-es emits the descriptor unpadded. Pad rather than appending a fixed `==`,
        # which only works because non-strict decoding discards what follows the padding.
        encoded = file_desc.group("blob")
        blob = base64.b64decode(encoded + "=" * (-len(encoded) % 4))
    except (binascii.Error, ValueError) as error:
        raise VerificationError(f"{relpath}: embedded descriptor is not valid base64") from error
    descriptor_file, descriptor_surface = decode_file_descriptor(blob)

    package = file_tag.group("package")
    # Keyed by the name relative to the package, matching how the descriptor names a declaration,
    # so a later lookup never has to reconstruct the qualified spelling and miss.
    blocks = {
        qualified.removeprefix(f"{package}."): block
        for qualified, block in _split_blocks(text).items()
    }
    messages: dict[str, tuple[Member, ...]] = {}
    enums: dict[str, tuple[Member, ...]] = {}
    services: dict[str, tuple[str, ...]] = {}
    for relative, block in blocks.items():
        if _TS_MESSAGE.search(block):
            messages[relative] = tuple(
                Member(m.group("name"), int(m.group("number"))) for m in _TS_FIELD.finditer(block)
            )
        elif _TS_ENUM.search(block):
            enums[relative] = tuple(
                Member(m.group("name"), int(m.group("number")))
                for m in _TS_ENUM_VALUE.finditer(block)
            )
        elif _TS_SERVICE.search(block):
            services[relative] = tuple(
                m.group("name").rsplit(".", 1)[1] for m in _TS_RPC.finditer(block)
            )
    return TypeScriptBinding(
        relpath=relpath,
        plugin_version=header.group("version"),
        plugin_parameter=header.group("parameter"),
        source_file=file_tag.group("file"),
        surface=Surface(
            package=package,
            syntax=file_tag.group("syntax"),
            messages=messages,
            enums=enums,
            services=services,
        ),
        descriptor_source_file=descriptor_file,
        descriptor_surface=descriptor_surface,
        blocks=blocks,
    )


def _lower_camel(name: str) -> str:
    """protobuf's JSON name: `page_size` -> `pageSize`, which is the emitted property name."""
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def _upper_snake(name: str) -> str:
    """`ErrorCode` -> `ERROR_CODE`, the prefix protobuf-es strips from enum value names."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def _field_member_pattern(camel: str) -> re.Pattern[str]:
    """Match the emitted member for one field, and nothing else in the block.

    Anchored to the start of a line, which is the whole point. An unanchored search for the
    camelCase name also matches the `* @generated from field: <type> <name> = <n>;` annotation
    that sits directly above the member whenever the proto name is a single word — 228 of this
    tree's 564 fields — so the comment satisfied the check and the TypeScript underneath was
    never read. Renaming `code:` to `codeRENAMED:` passed. Every line this can match now begins
    with a member, and an annotation line begins with `*`.

    Two shapes, because protobuf-es emits oneof members as a discriminated union rather than as
    properties: `pageSize: number`, `page?: PageRequest | undefined`, `seed?: bigint`, and
    `case: "artifactDigest"`. The `$` allows the suffix protobuf-es appends when a JSON name
    collides with a reserved word.
    """
    escaped = re.escape(camel)
    return re.compile(rf'^\s*(?:{escaped}\$?\??:|case: "{escaped}")', re.MULTILINE)


def _ts_identifier(dotted: str) -> str:
    """`BufferDescriptor.AccessMode` -> `BufferDescriptor_AccessMode`.

    TypeScript has no nested declarations, so protoc-gen-es flattens a nested message or enum by
    joining the path with an underscore.
    """
    return dotted.replace(".", "_")


# ---------------------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------------------


def _compare_surfaces(left_name: str, left: Surface, right_name: str, right: Surface) -> list[str]:
    errors: list[str] = []
    if left.package != right.package:
        errors.append(
            f"package: {left_name} says {left.package!r}, {right_name} says {right.package!r}"
        )
    if left.syntax != right.syntax:
        errors.append(
            f"syntax: {left_name} says {left.syntax!r}, {right_name} says {right.syntax!r}"
        )
    for kind, left_items, right_items in (
        ("message", left.messages, right.messages),
        ("enum", left.enums, right.enums),
        ("service", left.services, right.services),
    ):
        for name in sorted(set(left_items) - set(right_items)):
            errors.append(f"{kind} {name} is in {left_name} but not in {right_name}")
        for name in sorted(set(right_items) - set(left_items)):
            errors.append(f"{kind} {name} is in {right_name} but not in {left_name}")
        for name in sorted(set(left_items) & set(right_items)):
            left_members = left_items[name]
            right_members = right_items[name]
            rendered_left = _render_members(left_members)
            rendered_right = _render_members(right_members)
            if rendered_left != rendered_right:
                errors.append(
                    f"{kind} {name}: {left_name} declares [{', '.join(rendered_left)}] "
                    f"but {right_name} declares [{', '.join(rendered_right)}]"
                )
    return errors


def _render_members(members: Sequence[Member] | Sequence[str]) -> list[str]:
    return sorted(m.render() if isinstance(m, Member) else m for m in members)


# ---------------------------------------------------------------------------------------
# Static lane
# ---------------------------------------------------------------------------------------


def _read_gitattributes_rules(root: Path) -> set[str]:
    path = root / ".gitattributes"
    if not path.is_file():
        raise VerificationError(".gitattributes is missing; nothing declares generated artifacts")
    patterns: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        pattern, *attributes = stripped.split()
        if "linguist-generated=true" in attributes:
            patterns.add(pattern)
    return patterns


def check_generated_declarations(root: Path) -> list[str]:
    """Every generated artifact is declared generated, and every declaration has a disposition."""
    declared = _read_gitattributes_rules(root)
    claimed = {rule.pattern for rule in GENERATED_RULES}
    errors = [
        f".gitattributes marks {pattern!r} linguist-generated but "
        f"tools/codegen/verify_generated.py has no disposition for it. Add a GENERATED_RULES "
        f"entry saying whether it is regenerated, must be absent, or is unverifiable and why."
        for pattern in sorted(declared - claimed)
    ]
    errors.extend(
        f"GENERATED_RULES claims {pattern!r} but .gitattributes no longer marks it "
        f"linguist-generated; a generated artifact that stops being declared generated is "
        f"reviewed as source and verified by nothing."
        for pattern in sorted(claimed - declared)
    )
    return errors


def check_absent_artifacts(root: Path) -> list[str]:
    """Bindings that Bazel produces at build time must never be committed.

    `.gitattributes` already declares `protocols/**/*.pb.go` and friends generated, which is a
    rule with no tree behind it: there is no `protocols/gen` by design. Left alone it is a trap —
    the day one of those files is committed it arrives pre-collapsed in review and unverified by
    anything, because the only reason the rule was harmless is that the files did not exist.
    """
    errors: list[str] = []
    for rule in GENERATED_RULES:
        if rule.disposition != ABSENT:
            continue
        prefix, separator, leaf = rule.pattern.partition("/**/")
        if not separator or not leaf:
            # Raised rather than skipped: a pattern this loop cannot walk is a rule that silently
            # stops being enforced, which is the same defect as having no rule.
            raise VerificationError(
                f"GENERATED_RULES pattern {rule.pattern!r} is marked absent but is not of the "
                f"`<directory>/**/<glob>` form this check can walk"
            )
        for path in sorted((root / prefix).rglob(leaf)):
            if path.is_file():
                errors.append(
                    f"{path.relative_to(root).as_posix()} is committed, but {rule.reason}. "
                    f"Delete it and depend on the Bazel target instead."
                )
    return errors


def _proto_sources(root: Path) -> dict[str, Path]:
    base = root / PROTO_ROOT
    return {path.relative_to(base).as_posix(): path for path in sorted(base.rglob("*.proto"))}


def _typescript_bindings(root: Path) -> dict[str, Path]:
    base = root / TS_PROTO_ROOT
    return {path.relative_to(base).as_posix(): path for path in sorted(base.rglob("*_pb.ts"))}


def check_binding_bijection(root: Path) -> list[str]:
    """One `.proto` in, exactly one `_pb.ts` out, and nothing else in the generated tree."""
    protos = _proto_sources(root)
    bindings = _typescript_bindings(root)
    expected = {relpath[: -len(".proto")] + "_pb.ts" for relpath in protos}
    errors = [
        f"{PROTO_ROOT}/{name[: -len('_pb.ts')]}.proto has no generated "
        f"{TS_PROTO_ROOT}/{name}; run `pnpm generate`"
        for name in sorted(expected - set(bindings))
    ]
    errors.extend(
        f"{TS_PROTO_ROOT}/{name} has no source under {PROTO_ROOT}; it is an orphan of a deleted "
        f"or renamed contract and must be removed by `pnpm generate`"
        for name in sorted(set(bindings) - expected)
    )
    generated_root = root / TS_GENERATED_ROOT
    known = {root / TS_OPENAPI_FILE, *bindings.values()}
    errors.extend(
        f"{path.relative_to(root).as_posix()} sits in the generated tree but no generator in "
        f"tools/codegen produces it"
        for path in sorted(generated_root.rglob("*"))
        if path.is_file() and path not in known
    )
    if not (root / TS_OPENAPI_FILE).is_file():
        errors.append(f"{TS_OPENAPI_FILE} is missing; run `pnpm generate`")
    if not (root / OPENAPI_SOURCE).is_file():
        errors.append(f"{OPENAPI_SOURCE} is missing but {TS_OPENAPI_FILE} is generated from it")
    return errors


_EXACT_VERSION = re.compile(r"^\d+\.\d+\.\d+(?:[-+][\w.-]+)?$")


def _pinned_plugin_version(root: Path) -> str:
    """The exact protoc-gen-es version `package.json` pins.

    A range (`^2.14.0`, `~2.14.0`, `latest`) is rejected here rather than stripped down to a
    number. The generator stamps the version it actually ran into every file, so a range makes
    the stamp unverifiable — and stripping the specifier would compare the stamp against a
    version that `pnpm install` is free not to have installed, which is a check that looks like
    it works. The repository pins exactly today; this says so out loud.
    """
    manifest = json.loads((root / "package.json").read_text(encoding="utf-8"))
    for section in ("devDependencies", "dependencies"):
        version = str(manifest.get(section, {}).get(PROTOC_GEN_ES_PACKAGE, ""))
        if not version:
            continue
        if not _EXACT_VERSION.match(version):
            raise VerificationError(
                f"package.json pins {PROTOC_GEN_ES_PACKAGE} as {version!r}, which is a range. "
                f"The generated files record the version that produced them, so verifying them "
                f"needs an exact pin."
            )
        return version
    raise VerificationError(f"package.json does not pin {PROTOC_GEN_ES_PACKAGE}")


def _template_parameter(root: Path) -> str:
    """The `opt:` list protoc-gen-es is invoked with, as it records it in each file's header.

    Scoped to the `- local: protoc-gen-es` entry rather than to the first `opt:` in the file.
    Unscoped, adding any plugin ahead of protoc-gen-es would compare every binding's stamped
    parameter against a different plugin's options and fail the entire tree with a message that
    regeneration cannot satisfy.

    Read as text rather than with PyYAML: this lane runs inside `--static-only`, which is
    documented to have no third-party Python dependencies, and the block is a flat list of
    scalars under a single key.
    """
    text = (root / BUF_TEMPLATE).read_text(encoding="utf-8")
    match = re.search(
        rf"^  - local: {re.escape(PROTOC_GEN_ES_PLUGIN)}\n"
        rf"(?:    (?!opt:)\S.*\n)*"
        rf"    opt:\n(?P<items>(?:      - .*\n)+)",
        text,
        re.MULTILINE,
    )
    if match is None:
        raise VerificationError(
            f"{BUF_TEMPLATE} has no `opt:` list under its `- local: {PROTOC_GEN_ES_PLUGIN}` "
            f"plugin entry, so the parameter stamped into each generated file cannot be checked"
        )
    return ",".join(line.split("- ", 1)[1].strip() for line in match.group("items").splitlines())


def check_generated_bindings(root: Path) -> list[str]:
    """Cross-examine the three witnesses for every generated protobuf binding."""
    protos = _proto_sources(root)
    bindings = _typescript_bindings(root)
    pinned_version = _pinned_plugin_version(root)
    pinned_parameter = _template_parameter(root)
    errors: list[str] = []

    for name, path in bindings.items():
        relpath = f"{TS_PROTO_ROOT}/{name}"
        proto_relpath = name[: -len("_pb.ts")] + ".proto"
        try:
            binding = read_typescript_binding(path.read_text(encoding="utf-8"), relpath)
        except VerificationError as error:
            errors.append(str(error))
            continue

        if binding.plugin_version != pinned_version:
            errors.append(
                f"{relpath} was generated by protoc-gen-es v{binding.plugin_version} but "
                f"package.json pins {PROTOC_GEN_ES_PACKAGE} {pinned_version}; run `pnpm generate`"
            )
        if binding.plugin_parameter != pinned_parameter:
            errors.append(
                f"{relpath} was generated with parameter {binding.plugin_parameter!r} but "
                f"{BUF_TEMPLATE} now specifies {pinned_parameter!r}; run `pnpm generate`"
            )
        if binding.source_file != proto_relpath:
            errors.append(
                f"{relpath} claims to come from {binding.source_file!r} but its path in the "
                f"generated tree mirrors {proto_relpath!r}"
            )
        if binding.descriptor_source_file != proto_relpath:
            errors.append(
                f"{relpath}: the embedded descriptor was compiled from "
                f"{binding.descriptor_source_file!r}, not {proto_relpath!r}"
            )

        errors.extend(
            f"{relpath}: {message}"
            for message in _compare_surfaces(
                "the embedded descriptor",
                binding.descriptor_surface,
                "the emitted TypeScript",
                binding.surface,
            )
        )
        errors.extend(_check_declared_symbols(binding))

        source = protos.get(proto_relpath)
        if source is None:
            continue  # already reported by the bijection check
        try:
            declared = parse_proto_source(
                source.read_text(encoding="utf-8"), f"{PROTO_ROOT}/{proto_relpath}"
            )
        except VerificationError as error:
            errors.append(str(error))
            continue
        errors.extend(
            f"{PROTO_ROOT}/{proto_relpath} vs {relpath}: {message}"
            for message in _compare_surfaces(
                "the .proto source",
                declared,
                "the embedded descriptor",
                binding.descriptor_surface,
            )
        )
    return errors


def _check_declared_symbols(binding: TypeScriptBinding) -> list[str]:
    """The annotations must sit above declarations that actually carry the same names.

    The `@generated from ...` comments are the machine-readable half of the emitted file and the
    descriptor pins them. What they cannot pin on their own is the TypeScript underneath: a
    renamed property with its annotation left intact still type-checks, still lints, and still
    reads as generated. This is the check that catches an edit to the code rather than to its
    documentation.
    """
    errors: list[str] = []
    package = binding.surface.package
    for name, fields in binding.surface.messages.items():
        block = binding.blocks[name]
        symbol = _ts_identifier(name)
        if f'export type {symbol} = Message<"{package}.{name}">' not in block:
            errors.append(
                f"{binding.relpath}: message {name} has no matching "
                f'`export type {symbol} = Message<"{package}.{name}">` declaration'
            )
        if f"export const {symbol}Schema: GenMessage<{symbol}>" not in block:
            errors.append(
                f"{binding.relpath}: message {name} has no matching "
                f"`export const {symbol}Schema: GenMessage<{symbol}>` declaration"
            )
        for member in fields:
            camel = _lower_camel(member.name)
            if not _field_member_pattern(camel).search(block):
                errors.append(
                    f"{binding.relpath}: message {name} declares field {member.name!r} but the "
                    f"emitted TypeScript has no {camel!r} member; the annotation and the code "
                    f"disagree, which regeneration cannot produce"
                )
    for name, values in binding.surface.enums.items():
        block = binding.blocks[name]
        symbol = _ts_identifier(name)
        if f"export enum {symbol} {{" not in block:
            errors.append(
                f"{binding.relpath}: enum {name} has no matching `export enum {symbol}` declaration"
            )
        # protobuf-es drops the SCREAMING_SNAKE prefix derived from the enum's own name, which
        # is why `ERROR_CODE_NOT_FOUND` is emitted as `NOT_FOUND`. Accept either spelling: the
        # point is that the member exists under a name the value actually implies.
        prefix = f"{_upper_snake(name.rsplit('.', 1)[-1])}_"
        for member in values:
            stripped = member.name.removeprefix(prefix)
            pattern = rf"^\s*(?:{re.escape(stripped)}|{re.escape(member.name)}) = "
            if not re.search(pattern, block, re.MULTILINE):
                errors.append(
                    f"{binding.relpath}: enum {name} declares value {member.name!r} but the "
                    f"emitted TypeScript has no {stripped!r} member"
                )
    for name, methods in binding.surface.services.items():
        block = binding.blocks[name]
        if f"export const {name}: GenService<{{" not in block:
            errors.append(
                f"{binding.relpath}: service {name} has no matching "
                f"`export const {name}: GenService<...>` declaration"
            )
        for method in methods:
            camel = _lower_camel(method[:1].lower() + method[1:])
            if not re.search(rf"^\s*{re.escape(camel)}: \{{", block, re.MULTILINE):
                errors.append(
                    f"{binding.relpath}: service {name} declares rpc {method!r} but the emitted "
                    f"TypeScript has no {camel!r} method"
                )
    return errors


_OPENAPI_BANNER = "This file was auto-generated by openapi-typescript."
_OPENAPI_PATH_LINE = re.compile(r"^  (?P<path>/\S*):\s*$")


def _openapi_paths(root: Path) -> list[str]:
    """The keys of the top-level `paths:` mapping, read as text.

    A two-space-indented `/...:` line inside the `paths:` block, which is the only shape the
    contract uses and the only one `buf`/Spectral would accept. Read lexically for the same
    reason as `_template_parameter`: the static lane owns no YAML parser.
    """
    text = (root / OPENAPI_SOURCE).read_text(encoding="utf-8")
    paths: list[str] = []
    inside = False
    for line in text.splitlines():
        if line.startswith("paths:"):
            inside = True
            continue
        if inside:
            if line and not line.startswith((" ", "\t", "#")):
                break
            match = _OPENAPI_PATH_LINE.match(line)
            if match:
                paths.append(match.group("path"))
    return paths


def check_openapi_binding(root: Path) -> list[str]:
    """The generated OpenAPI client exposes exactly the operations the contract declares."""
    target = root / TS_OPENAPI_FILE
    if not target.is_file() or not (root / OPENAPI_SOURCE).is_file():
        return []  # already reported by the bijection check
    text = target.read_text(encoding="utf-8")
    if _OPENAPI_BANNER not in text:
        return [
            f"{TS_OPENAPI_FILE} has no openapi-typescript banner; it was not produced by the "
            f"generator. Run `pnpm generate`."
        ]
    match = re.search(r"export interface paths \{(?P<body>.*?)\n\}", text, re.DOTALL)
    if match is None:
        return [f"{TS_OPENAPI_FILE} has no `export interface paths` block; run `pnpm generate`"]
    emitted = set(re.findall(r'^    "(?P<path>/[^"]*)":', match.group("body"), re.MULTILINE))
    declared = set(_openapi_paths(root))
    errors = [
        f"{OPENAPI_SOURCE} declares path {path!r} but {TS_OPENAPI_FILE} does not expose it; "
        f"run `pnpm generate`"
        for path in sorted(declared - emitted)
    ]
    errors.extend(
        f"{TS_OPENAPI_FILE} exposes path {path!r} that {OPENAPI_SOURCE} no longer declares; "
        f"run `pnpm generate`"
        for path in sorted(emitted - declared)
    )
    return errors


STATIC_CHECKS = (
    ("generated declarations", check_generated_declarations),
    ("build-time bindings absent", check_absent_artifacts),
    ("protobuf binding bijection", check_binding_bijection),
    ("protobuf binding contents", check_generated_bindings),
    ("OpenAPI client contents", check_openapi_binding),
)


def check(root: Path) -> list[str]:
    """The hermetic lane, in the shape `run_architecture_checks.py` expects.

    Wraps each checker so an unreadable witness is reported as a failure. A gate that returns no
    errors because it could not look is the failure mode this file was written against.
    """
    errors: list[str] = []
    for name, checker in STATIC_CHECKS:
        try:
            errors.extend(checker(root))
        except (VerificationError, OSError, ValueError) as error:
            errors.append(f"{name} could not be verified: {error}")
    return errors


# ---------------------------------------------------------------------------------------
# Regeneration lane
# ---------------------------------------------------------------------------------------


def _generate_into(root: Path, destination: Path) -> None:
    """Run the pinned generators with `destination` as their output prefix."""
    bin_dir = root / "node_modules" / ".bin"
    buf = bin_dir / "buf"
    openapi = bin_dir / "openapi-typescript"
    for tool in (buf, openapi):
        if not tool.exists():
            raise VerificationError(
                f"{tool.relative_to(root).as_posix()} is missing. Regeneration needs the pinned "
                f"Node toolchain: `tools/dev/nixw develop .#default --command pnpm install "
                f"--frozen-lockfile`, then rerun."
            )
    # `pnpm exec` re-runs `pnpm install` before the command, which both mutates the tree and
    # fails on ignored build scripts. Invoke the pinned binaries directly and put `.bin` on PATH
    # so `buf` can find `protoc-gen-es`, which is how buf resolves a `local:` plugin.
    env = dict(os.environ)
    env["PATH"] = os.pathsep.join([str(bin_dir), env.get("PATH", "")])
    subprocess.run(
        [str(buf), "generate", "protocols", "--template", BUF_TEMPLATE, "-o", str(destination)],
        cwd=root,
        env=env,
        check=True,
    )
    subprocess.run(
        [str(openapi), OPENAPI_SOURCE, "-o", str(destination / TS_OPENAPI_FILE)],
        cwd=root,
        env=env,
        check=True,
    )


def _tree(base: Path, prefix: str) -> dict[str, bytes]:
    """Map repository-relative path to content, so a finding names the file a reader can open."""
    return {
        f"{prefix}/{path.relative_to(base).as_posix()}": path.read_bytes()
        for path in sorted(base.rglob("*"))
        if path.is_file()
    }


def _diff(relpath: str, committed: bytes, regenerated: bytes) -> str:
    """One finding, rendered as a bounded unified diff of committed against generated."""
    headline = (
        f"{relpath}: committed content differs from regenerated output "
        f"(a/ is committed, b/ is generated):"
    )
    try:
        committed_lines = committed.decode("utf-8").splitlines(keepends=True)
        regenerated_lines = regenerated.decode("utf-8").splitlines(keepends=True)
    except UnicodeDecodeError:
        return f"{relpath}: committed binary content differs from regenerated output"
    lines = list(
        difflib.unified_diff(
            committed_lines,
            regenerated_lines,
            fromfile=f"a/{relpath}",
            tofile=f"b/{relpath}",
            n=2,
        )
    )
    rendered = [f"  {line.rstrip()}" for line in lines[:MAX_DIFF_LINES]]
    if len(lines) > MAX_DIFF_LINES:
        rendered.append(f"  ... {len(lines) - MAX_DIFF_LINES} further diff line(s) suppressed")
    return "\n".join([headline, *rendered])


def compare_trees(committed: dict[str, bytes], regenerated: dict[str, bytes]) -> list[str]:
    """Report every way the committed tree differs from freshly generated output.

    Each finding is one string, multi-line where it carries a diff, so the failure count at the
    end names files rather than diff lines.
    """
    errors: list[str] = [
        f"{relpath}: generated but not committed; run `pnpm generate`"
        for relpath in sorted(set(regenerated) - set(committed))
    ]
    errors.extend(
        f"{relpath}: committed but no generator produces it; run `pnpm generate`"
        for relpath in sorted(set(committed) - set(regenerated))
    )
    differing = [
        relpath
        for relpath in sorted(set(committed) & set(regenerated))
        if committed[relpath] != regenerated[relpath]
    ]
    errors.extend(
        _diff(relpath, committed[relpath], regenerated[relpath])
        for relpath in differing[:MAX_DIFF_FILES]
    )
    if len(differing) > MAX_DIFF_FILES:
        errors.append(
            f"... and {len(differing) - MAX_DIFF_FILES} further file(s) differ; "
            f"run `pnpm generate` and review the whole diff"
        )
    return errors


def check_regenerated(root: Path, *, repeat: bool = False) -> list[str]:
    """Regenerate into a temporary tree and byte-compare, never touching the working tree."""
    with tempfile.TemporaryDirectory(prefix="mindclade-verify-generated-") as temporary:
        first = Path(temporary) / "first"
        first.mkdir()
        _generate_into(root, first)
        regenerated = _tree(first / TS_GENERATED_ROOT, TS_GENERATED_ROOT)
        errors = compare_trees(_tree(root / TS_GENERATED_ROOT, TS_GENERATED_ROOT), regenerated)
        if repeat:
            second = Path(temporary) / "second"
            second.mkdir()
            _generate_into(root, second)
            repeated = _tree(second / TS_GENERATED_ROOT, TS_GENERATED_ROOT)
            # The union, not the second pass. Iterating only what the second pass emitted would
            # report a generator that drops an output on some runs as perfectly stable, which is
            # the exact nondeterminism this flag exists to rule out before trusting the bytes.
            for relpath in sorted(set(regenerated) | set(repeated)):
                if regenerated.get(relpath) != repeated.get(relpath):
                    errors.append(
                        f"{relpath}: two generation passes over identical inputs disagree, so "
                        f"byte comparison cannot gate this artifact"
                    )
    return errors


# ---------------------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------------------


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--repo", type=Path, default=ROOT)
    parser.add_argument(
        "--mode",
        choices=("static", "regenerate", "all"),
        default="all",
        help="static is hermetic and is what presubmit runs; regenerate needs node_modules",
    )
    parser.add_argument(
        "--repeat",
        action="store_true",
        help="generate twice and compare the passes, proving generation is deterministic",
    )
    args = parser.parse_args(argv)
    root = args.repo.resolve()

    errors: list[str] = []
    if args.mode in ("static", "all"):
        for name, checker in STATIC_CHECKS:
            try:
                found = checker(root)
            except (VerificationError, OSError, ValueError) as error:
                found = [f"{name} could not be verified: {error}"]
            if found:
                errors.extend(f"{name}: {message}" for message in found)
            else:
                print(f"PASS {name}")
    if args.mode in ("regenerate", "all"):
        try:
            found = check_regenerated(root, repeat=args.repeat)
        except (VerificationError, OSError, subprocess.CalledProcessError) as error:
            found = [f"regeneration failed: {error}"]
        if found:
            errors.extend(f"regenerated output: {message}" for message in found)
        else:
            print("PASS regenerated output")

    for message in errors:
        print(message, file=sys.stderr)
    if errors:
        print(
            f"generated-artifact verification failed with {len(errors)} finding(s)", file=sys.stderr
        )
        return 1
    print("generated artifacts match protocols/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
