# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "cachetest",
    srcs = [
        "conformance.go",
        "doc.go",
    ],
    importpath = "mindclade.internal/libs/go/storage/cache/cachetest",
    deps = [
        "//libs/go/faults",
        "//libs/go/storage/cache",
    ],
    testonly = True,
)
