# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "workqueuetest",
    testonly = True,
    srcs = [
        "conformance.go",
        "doc.go",
    ],
    importpath = "go.mindclade.dev/libs/go/coordination/workqueue/workqueuetest",
    deps = [
        "//libs/go/coordination/workqueue",
        "//libs/go/requestmeta",
    ],
)
