# Copyright 2026 Mindclade. All rights reserved.
# Confidential, proprietary, and trade-secret information.

load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "workqueuetest",
    srcs = ["conformance.go", "doc.go"],
    importpath = "mindclade.internal/libs/go/coordination/workqueue/workqueuetest",
    deps = [
        "//libs/go/coordination/workqueue",
        "//libs/go/requestmeta",
    ],
    testonly = True,
)
