# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("//tools/build:pytest.bzl", "pytest_test")

pytest_test(
    name = "test_api",
    srcs = ["test_api.py"],
    imports = ["../../.."],
    deps = [
        "//kernels",
        "//kernels:kernel_core",
        "//kernels/api",
    ],
)
