# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

package(default_visibility = ["//visibility:private"])

test_suite(
    name = "generated_go_test",
    tests = ["//protocols/consumers/_bazel:generated_go_test"],
)
