# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_python//python:defs.bzl", "py_library")
load("//tools/build:pytest.bzl", "pytest_test")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "fixtures",
    srcs = [
        "__init__.py",
        "fixtures.py",
    ],
    imports = ["../../.."],
    deps = [
        "//data",
        "//data/contracts",
        "//data/datasets",
    ],
)

[
    pytest_test(
        name = name,
        srcs = [name + ".py"],
        data = ["//data/datasets:examples"],
        imports = ["../../.."],
        deps = [
            ":fixtures",
            "//data",
            "//data/contracts",
            "//data/datasets",
        ],
    )
    for name in [
        "test_catalog",
        "test_resolver",
    ]
]
