# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:private"])

filegroup(
    name = "scaffold_files",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)

sh_test(
    name = "terraform_test",
    srcs = ["tests/bazel_test.sh"],
    data = [
        ":scaffold_files",
        "@mindclade_infra_validation_tools//:bin/.tool-root",
        "@mindclade_infra_validation_tools//:tools",
        "@mindclade_terraform_google_provider//:provider",
        "@mindclade_terraform_google_provider//:provider_root",
    ],
    env = {
        "MINDCLADE_TERRAFORM_GOOGLE_PROVIDER_MARKER_RLOCATION": "$(rlocationpath @mindclade_terraform_google_provider//:provider_root)",
        "MINDCLADE_VALIDATION_TOOL_MARKER_RLOCATION": "$(rlocationpath @mindclade_infra_validation_tools//:bin/.tool-root)",
    },
    tags = ["terraform"],
)
