# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("//tools/build/bazel:terraform_test.bzl", "terraform_test")

package(default_visibility = ["//visibility:private"])

filegroup(
    name = "scaffold_files",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)

terraform_test(
    name = "terraform_test",
    module_files = [":scaffold_files"],
)
