# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

package(default_visibility = ["//visibility:private"])

load("//tools/build:pytest.bzl", "pytest_test")

pytest_test(
    name = "test_contracts",
    srcs = ["test_contracts.py"],
    imports = ["../../.."],
    deps = ["//data/contracts:contracts"],
)

filegroup(
    name = "scaffold_files",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)
