# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

load("//tools/build:pytest.bzl", "pytest_test")

pytest_test(
    name = "test_provider",
    srcs = [
        "__init__.py",
        "test_provider.py",
    ],
    imports = ["../../../.."],
    deps = [
        "//kernels",
        "//kernels/api",
        "//kernels/providers/tilelang",
        "//kernels/tilelang/targets",
    ],
)
