# Copyright 2026 Mindclade. All rights reserved.
# Confidential and proprietary.

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "events",
    srcs = [
        "doc.go",
        "recorder.go",
    ],
    importpath = "mindclade.internal/libs/go/kubernetes/events",
    deps = [
        "//libs/go/faults",
        "//libs/go/kubernetes",
        "//libs/go/kubernetes/metadata",
        "//libs/go/requestmeta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_client_go//tools/record",
    ],
)

go_test(
    name = "events_test",
    srcs = ["recorder_test.go"],
    embed = [":events"],
    deps = [
        "//libs/go/faults",
        "//libs/go/kubernetes/metadata",
        "//libs/go/requestmeta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1",
        "@io_k8s_apimachinery//pkg/runtime",
    ],
)
