# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: mindclade-platform
      mindclade.dev/owner: security-engineering
