# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("//tools/build:pytest.bzl", "pytest_test")

package(default_visibility = ["//visibility:private"])

[
    pytest_test(
        name = source.removesuffix(".py"),
        srcs = [source],
        imports = ["../../../.."],
        deps = [
            "//libs/python/errors",
            "//libs/python/testing",
            "@pypi//numpy",
        ],
    )
    for source in [
        "test_helpers.py",
        "test_numerics.py",
        "test_processes.py",
    ]
]
