# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

"""Fail-closed affected Bazel selection and evidence-producing execution.

Bazel's post-loading graph is the dependency authority. This module maps changed
files to conservative owning-package seeds, asks Bazel for reverse dependencies,
and executes configured analysis and tests over the resulting target files.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
import shlex
import stat
import subprocess
import sys
import time
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from typing import Any

from ci.common.affected_contract import ContractError, GlobalInputContract
from ci.common.affected_contract import load_global_input_contract as _load_global_input_contract

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_VERSION = 1
FULL_TARGET = "//..."
LATENCY_SLO_SECONDS = 30 * 60
GRAPH_NATIVE_AFFECTED_ACTIVE = False
GLOBAL_INPUT_CONTRACT_PATH = ROOT / "ci/common/affected_global_inputs.json"
NIX_STORE_ROOT = Path("/nix/store")
STRUCTURAL_STATUSES = frozenset({"C", "D", "R", "T", "U", "X", "B"})
VALID_CHANGE_STATUSES = STRUCTURAL_STATUSES | {"A", "M"}
PACKAGE_BOUNDARY_FILES = frozenset({"BUILD", "BUILD.bazel"})
BAZELRC_HEADER = "# Generated by CI; contains no credentials."
DISK_BAZELRC_FIXED_LINES = (
    "build --noremote_cache_async",
    "build --remote_verify_downloads",
    "build --remote_cache_compression",
    "build --experimental_disk_cache_gc_max_size=1G",
    "build --experimental_disk_cache_gc_idle_delay=1s",
)
REMOTE_CACHE_ENDPOINT = "http://127.0.0.1:8085"
REMOTE_BAZELRC_FIXED_LINES = (
    "build --remote_verify_downloads",
    "build --noremote_cache_async",
    "build --remote_timeout=60s",
    "build --remote_retries=3",
)
WORKSPACE_BAZELRC_IMPORT = ("try-import", "%workspace%/user.bazelrc")
CACHE_ROLE_BY_ROUTE = {
    ("disk", "pull_request"): "reader",
    ("disk", "merge_group"): "reader",
    ("disk", "push"): "writer",
    ("disk", "schedule"): "writer",
    ("disk", "workflow_dispatch"): "writer",
    ("remote", "pull_request"): "reader",
    ("remote", "merge_group"): "writer",
    ("remote", "push"): "writer",
    ("remote", "schedule"): "writer",
}
SANITIZED_BUILD_ENVIRONMENT = frozenset(
    {
        "BAZELISK_GITHUB_TOKEN",
        "BAZEL_OPTS",
        "BAZEL_STARTUP_OPTIONS",
        "JDK_JAVA_OPTIONS",
        "JAVA_TOOL_OPTIONS",
        "_JAVA_OPTIONS",
    }
)

RUST_PREFIXES = (
    "libs/rust/",
    "protocols/rust/",
    "protocols/proto/mindclade/runtime/",
    "services/runtime_gateway/",
    "services/runtime_host/",
    "services/artifact_proxy/",
    "services/node_agent/",
    "services/workers/ingestion/",
    "serving/runtime/",
    "Cargo.toml",
    "Cargo.lock",
    "deny.toml",
    "security/rust-supply-chain.toml",
    "tools/qualification/rust/",
    "tools/build/nix/",
    "flake.nix",
    "flake.lock",
)


class SelectionError(ContractError):
    """The affected set could not be established authoritatively."""


def load_global_input_contract(path: Path = GLOBAL_INPUT_CONTRACT_PATH) -> GlobalInputContract:
    """Load the shared contract while preserving the selector's public error type."""
    try:
        return _load_global_input_contract(path)
    except ContractError as error:
        raise SelectionError(error.code, error.public_message) from error


def resolve_selection_mode(
    requested_mode: str,
    *,
    event: str,
    ref: str | None,
    base_sha: str | None,
) -> str:
    """Resolve protected workflow events to their only permitted selection mode."""

    if requested_mode not in {"auto", "affected", "full"}:
        raise SelectionError("AFFECTED-SELECT-001", "selection mode is unsupported")

    expected_mode: str | None
    if event == "pull_request":
        expected_mode = "affected" if GRAPH_NATIVE_AFFECTED_ACTIVE else "full"
    elif event == "merge_group":
        expected_mode = "full"
    elif event in {"push", "schedule", "workflow_dispatch"}:
        if ref != "refs/heads/main":
            raise SelectionError("AFFECTED-SELECT-009", "protected workflow ref is not authorized")
        expected_mode = "full"
    elif event == "local":
        expected_mode = None
    else:
        raise SelectionError("AFFECTED-SELECT-009", "workflow event is not authorized")

    if requested_mode == "auto":
        if expected_mode is None:
            raise SelectionError("AFFECTED-SELECT-010", "local selection requires an explicit mode")
        resolved_mode = expected_mode
    else:
        resolved_mode = requested_mode
        if expected_mode is not None and requested_mode != expected_mode:
            raise SelectionError(
                "AFFECTED-SELECT-010", "selection mode conflicts with workflow policy"
            )
    if resolved_mode == "affected" and not (base_sha or "").strip():
        raise SelectionError(
            "AFFECTED-SELECT-011", "affected selection requires an explicit base revision"
        )
    return resolved_mode


@dataclass(frozen=True)
class Change:
    status: str
    path: str
    old_path: str | None = None

    def as_dict(self) -> dict[str, str]:
        payload = {"status": self.status, "path": self.path}
        if self.old_path is not None:
            payload["old_path"] = self.old_path
        return payload


@dataclass(frozen=True)
class _FileAuthority:
    path: Path
    identity: tuple[int, int, int, int, int]
    sha256: str


@dataclass(frozen=True)
class BazelrcAuthority:
    """Validated identities and contents for Bazel's two workspace rc files."""

    root: Path
    workspace: _FileAuthority
    generated: _FileAuthority

    def assert_unchanged(self, *, root: Path) -> None:
        if root != self.root:
            raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")
        try:
            current_workspace, _ = _read_authority_file(self.workspace.path)
            current_generated, _ = _read_authority_file(self.generated.path)
        except OSError as error:
            raise SelectionError(
                "AFFECTED-SELECT-020", "Bazel runtime contract is invalid"
            ) from error
        if current_workspace != self.workspace or current_generated != self.generated:
            raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")


def _read_authority_file(path: Path) -> tuple[_FileAuthority, bytes]:
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        descriptor = os.open(path, flags)
        with os.fdopen(descriptor, "rb") as stream:
            descriptor = -1
            before = os.fstat(stream.fileno())
            if not stat.S_ISREG(before.st_mode) or before.st_mode & 0o022:
                raise OSError("invalid authority file")
            payload = stream.read(1024 * 1024 + 1)
            after = os.fstat(stream.fileno())
        current = path.lstat()
    except OSError:
        if descriptor >= 0:
            os.close(descriptor)
        raise
    if len(payload) > 1024 * 1024:
        raise OSError("authority file is too large")
    before_identity = (
        before.st_dev,
        before.st_ino,
        before.st_mode,
        before.st_size,
        before.st_mtime_ns,
    )
    after_identity = (
        after.st_dev,
        after.st_ino,
        after.st_mode,
        after.st_size,
        after.st_mtime_ns,
    )
    path_identity = (
        current.st_dev,
        current.st_ino,
        current.st_mode,
        current.st_size,
        current.st_mtime_ns,
    )
    if before_identity != after_identity or before_identity != path_identity:
        raise OSError("authority file changed while reading")
    return (
        _FileAuthority(
            path=path,
            identity=before_identity,
            sha256=hashlib.sha256(payload).hexdigest(),
        ),
        payload,
    )


@dataclass(frozen=True)
class Selection:
    mode: str
    reason: str
    changes: tuple[Change, ...]
    seeds: tuple[str, ...]
    analysis_targets: tuple[str, ...]
    test_targets: tuple[str, ...]
    base_sha: str | None
    head_sha: str
    event: str
    analysis_query: str | None = None
    test_query: str | None = None
    partition: dict[str, Any] | None = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "schema_version": SCHEMA_VERSION,
            "base_sha": self.base_sha,
            "head_sha": self.head_sha,
            "event": self.event,
            "mode": self.mode,
            "reason": self.reason,
            "changed_paths": [change.as_dict() for change in self.changes],
            "seeds": list(self.seeds),
            "analysis_targets": list(self.analysis_targets),
            "test_targets": list(self.test_targets),
            "counts": {
                "changed_paths": len(self.changes),
                "seeds": len(self.seeds),
                "analysis_targets": len(self.analysis_targets),
                "test_targets": len(self.test_targets),
            },
            "queries": {"analysis": self.analysis_query, "test": self.test_query},
            "partition": self.partition,
        }


Query = Callable[[str], Sequence[str]]


def utc_now() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _normalize_path(raw: str) -> str:
    path = PurePosixPath(raw)
    if (
        path.is_absolute()
        or not raw
        or "\\" in raw
        or any(ord(character) < 32 or ord(character) == 127 for character in raw)
        or ".." in path.parts
    ):
        raise SelectionError("AFFECTED-SELECT-002", "changed path is unsafe")
    normalized = path.as_posix()
    if normalized == ".":
        raise SelectionError("AFFECTED-SELECT-002", "changed path is unsafe")
    return normalized


def _normalize_changes(changes: Iterable[Change | str]) -> tuple[Change, ...]:
    normalized: list[Change] = []
    for item in changes:
        change = item if isinstance(item, Change) else Change(status="M", path=item)
        status = change.status[:1].upper()
        if status not in VALID_CHANGE_STATUSES:
            raise SelectionError("AFFECTED-SELECT-012", "changed-path status is invalid")
        normalized.append(
            Change(
                status=status,
                path=_normalize_path(change.path),
                old_path=_normalize_path(change.old_path) if change.old_path else None,
            )
        )
    return tuple(normalized)


def rust_qualification_required(changed: Iterable[Change | str]) -> bool:
    changes = _normalize_changes(changed)
    return not changes or any(
        change.path == prefix or change.path.startswith(prefix)
        for change in changes
        for prefix in RUST_PREFIXES
    )


def trusted_git_launcher() -> Path:
    """Return the read-only Nix-store Git selected by the CI shell."""

    value = os.environ.get("MINDCLADE_GIT", "")
    launcher = Path(value)
    try:
        relative = launcher.relative_to(NIX_STORE_ROOT)
        if (
            not value
            or not launcher.is_absolute()
            or ".." in launcher.parts
            or len(relative.parts) < 2
            or launcher.resolve(strict=True) != launcher
            or not launcher.is_file()
            or not launcher.stat().st_mode & 0o111
        ):
            raise OSError("invalid launcher")
        current = NIX_STORE_ROOT / relative.parts[0]
        for part in relative.parts[1:]:
            if current.is_symlink() or current.stat().st_mode & 0o222:
                raise OSError("mutable launcher")
            current /= part
        if current.is_symlink() or current.stat().st_mode & 0o222:
            raise OSError("mutable launcher")
    except (OSError, RuntimeError, ValueError) as error:
        raise SelectionError("AFFECTED-SELECT-022", "trusted Git launcher is invalid") from error
    return launcher


def _git_environment() -> dict[str, str]:
    return {
        "GIT_CONFIG_GLOBAL": os.devnull,
        "GIT_CONFIG_NOSYSTEM": "1",
        "GIT_NO_REPLACE_OBJECTS": "1",
        "GIT_OPTIONAL_LOCKS": "0",
        "GIT_TERMINAL_PROMPT": "0",
        "LANG": "C",
        "LC_ALL": "C",
    }


def _assert_no_symlink_components(path: Path) -> None:
    if not path.is_absolute():
        raise OSError("noncanonical path")
    current = Path(path.anchor)
    for part in path.parts[1:]:
        current /= part
        if current.is_symlink():
            raise OSError("symlinked path")


def _read_strict_git_path(path: Path) -> Path:
    if path.is_symlink() or not path.is_file():
        raise OSError("invalid Git path file")
    payload = path.read_bytes()
    if len(payload) > 4096 or b"\0" in payload:
        raise OSError("invalid Git path file")
    decoded = payload.decode("utf-8", errors="strict").removesuffix("\n")
    if not decoded or "\n" in decoded:
        raise OSError("invalid Git path file")
    candidate = Path(decoded)
    if not candidate.is_absolute():
        candidate = path.parent / candidate
    canonical = Path(os.path.abspath(candidate))
    _assert_no_symlink_components(canonical)
    if canonical.resolve(strict=True) != canonical:
        raise OSError("noncanonical Git path")
    return canonical


def _canonical_git_context(root: Path) -> tuple[Path, Path]:
    """Resolve one explicit work tree and its non-symlink Git metadata directory."""

    try:
        if not root.is_absolute() or root.is_symlink():
            raise OSError("noncanonical work tree")
        workspace = root.resolve(strict=True)
        if workspace != root or not workspace.is_dir():
            raise OSError("noncanonical work tree")

        dot_git = workspace / ".git"
        metadata = dot_git.lstat()
        if stat.S_ISDIR(metadata.st_mode):
            git_dir = dot_git.resolve(strict=True)
        elif stat.S_ISREG(metadata.st_mode):
            payload = dot_git.read_bytes()
            if len(payload) > 4096 or b"\0" in payload:
                raise OSError("invalid Git file")
            line = payload.decode("utf-8", errors="strict").removesuffix("\n")
            if "\n" in line or not line.startswith("gitdir: "):
                raise OSError("invalid Git file")
            pointer = Path(line.removeprefix("gitdir: "))
            if not pointer.is_absolute():
                pointer = dot_git.parent / pointer
            pointer = Path(os.path.abspath(pointer))
            _assert_no_symlink_components(pointer)
            git_dir = pointer.resolve(strict=True)
            common_dir = _read_strict_git_path(git_dir / "commondir")
            if (
                common_dir.name != ".git"
                or git_dir.parent.name != "worktrees"
                or git_dir.parent.parent != common_dir
            ):
                raise OSError("invalid linked work tree")
            back_pointer = git_dir / "gitdir"
            linked_dot_git = _read_strict_git_path(back_pointer)
            if linked_dot_git != dot_git:
                raise OSError("invalid linked work tree")
        else:
            raise OSError("invalid Git metadata")
        if git_dir.is_symlink() or not git_dir.is_dir():
            raise OSError("invalid Git metadata")
    except (OSError, RuntimeError, UnicodeError, ValueError) as error:
        raise SelectionError("AFFECTED-SELECT-003", "Git metadata is unavailable") from error
    return workspace, git_dir


def run_git(args: Sequence[str], *, root: Path = ROOT) -> subprocess.CompletedProcess[bytes]:
    launcher = trusted_git_launcher()
    try:
        if not root.is_absolute() or root.is_symlink():
            raise OSError("noncanonical work tree")
        workspace = root.resolve(strict=True)
        if workspace != root or not workspace.is_dir():
            raise OSError("noncanonical work tree")
        command = [str(launcher)]
        try:
            (workspace / ".git").lstat()
        except FileNotFoundError:
            if not args or args[0] != "init":
                raise OSError("missing Git metadata") from None
        else:
            workspace, git_dir = _canonical_git_context(workspace)
            command.extend(
                [
                    f"--git-dir={git_dir}",
                    f"--work-tree={workspace}",
                ]
            )
        command.extend(
            [
                "-c",
                "core.bare=false",
                "-c",
                "core.hooksPath=/dev/null",
                "-c",
                "core.fsmonitor=false",
                "-c",
                "core.untrackedCache=false",
                *args,
            ]
        )
        return subprocess.run(
            command,
            cwd=workspace,
            env=_git_environment(),
            check=False,
            capture_output=True,
        )
    except (OSError, ValueError) as error:
        raise SelectionError("AFFECTED-SELECT-003", "Git metadata is unavailable") from error


def git_revision(revision: str, *, root: Path = ROOT) -> str:
    result = run_git(
        ["rev-parse", "--verify", "--end-of-options", f"{revision}^{{commit}}"],
        root=root,
    )
    if result.returncode:
        raise SelectionError("AFFECTED-SELECT-003", "Git revision is unavailable")
    try:
        payload = result.stdout
        if len(payload) not in {41, 65} or not payload.endswith(b"\n"):
            raise ValueError("noncanonical revision")
        value = payload[:-1].decode("ascii", errors="strict")
        if value != value.lower() or any(
            character not in "0123456789abcdef" for character in value
        ):
            raise ValueError("noncanonical revision")
        return value
    except UnicodeError as error:
        raise SelectionError("AFFECTED-SELECT-003", "Git revision is unavailable") from error
    except ValueError as error:
        raise SelectionError("AFFECTED-SELECT-003", "Git revision is unavailable") from error


def _assert_canonical_checkout_metadata(root: Path) -> None:
    try:
        metadata = (root / ".git").lstat()
        if not stat.S_ISDIR(metadata.st_mode):
            raise OSError("governed checkout uses external Git metadata")
    except OSError as error:
        raise SelectionError(
            "AFFECTED-SELECT-019", "checkout integrity validation failed"
        ) from error
    try:
        checkout, git_dir = _canonical_git_context(root)
    except (OSError, RuntimeError, SelectionError, ValueError) as error:
        raise SelectionError(
            "AFFECTED-SELECT-019", "checkout integrity validation failed"
        ) from error
    result = run_git(
        [
            "rev-parse",
            "--path-format=absolute",
            "--show-toplevel",
            "--absolute-git-dir",
            "--is-bare-repository",
        ],
        root=checkout,
    )
    try:
        values = result.stdout.decode("utf-8", errors="strict").splitlines()
    except UnicodeError as error:
        raise SelectionError(
            "AFFECTED-SELECT-019", "checkout integrity validation failed"
        ) from error
    if result.returncode or values != [str(checkout), str(git_dir), "false"]:
        raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")


def _git_paths(command: Sequence[str], *, root: Path) -> tuple[str, ...]:
    result = run_git(command, root=root)
    if result.returncode:
        raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
    try:
        return tuple(
            _normalize_path(field.decode("utf-8", errors="strict"))
            for field in result.stdout.split(b"\0")
            if field
        )
    except (UnicodeError, SelectionError) as error:
        raise SelectionError(
            "AFFECTED-SELECT-019", "checkout integrity validation failed"
        ) from error


def _safe_bazel_output_symlink(relative: str, *, root: Path) -> bool:
    allowed = {"bazel-bin", "bazel-out", "bazel-testlogs", f"bazel-{root.name}"}
    if relative not in allowed:
        return False
    candidate = root / relative
    try:
        raw_target = Path(os.readlink(candidate))
        resolved = candidate.resolve(strict=True)
        resolved_root = root.resolve(strict=True)
    except (OSError, RuntimeError, ValueError):
        return False
    if (
        not raw_target.is_absolute()
        or not resolved.is_dir()
        or resolved.is_relative_to(resolved_root)
    ):
        return False

    parts = resolved.parts
    positions = [index for index, part in enumerate(parts) if part == "execroot"]
    if len(positions) != 1:
        return False
    index = positions[0]
    # Require at least one path component before execroot so the target cannot
    # be something like /execroot/_main. A custom --output_base (e.g. the
    # /home/runner/.bazel path set by the GitHub-hosted runner) produces a
    # shorter prefix than the default _bazel_<user>/<hash> layout; the
    # structural checks below (absolute, outside workspace, execroot suffix)
    # are sufficient to establish legitimacy without hard-coding one layout.
    if index < 1:
        return False

    suffix = parts[index:]
    if relative == f"bazel-{root.name}":
        return suffix == ("execroot", "_main")
    if relative == "bazel-out":
        return suffix == ("execroot", "_main", "bazel-out")
    if len(suffix) != 5 or suffix[:3] != ("execroot", "_main", "bazel-out"):
        return False
    expected_leaf = "bin" if relative == "bazel-bin" else "testlogs"
    return bool(suffix[3]) and suffix[4] == expected_leaf


def _assert_no_untracked_directories(tracked: tuple[str, ...], *, root: Path) -> None:
    tracked_directories = {""}
    for relative in tracked:
        parent = PurePosixPath(relative).parent
        while parent.as_posix() != ".":
            tracked_directories.add(parent.as_posix())
            parent = parent.parent

    def raise_walk_error(error: OSError) -> None:
        raise error

    try:
        for current, directories, _files in os.walk(
            root,
            topdown=True,
            followlinks=False,
            onerror=raise_walk_error,
        ):
            current_path = Path(current)
            retained: list[str] = []
            for directory in directories:
                candidate = current_path / directory
                relative = candidate.relative_to(root).as_posix()
                if relative == ".git" or candidate.is_symlink():
                    continue
                if relative not in tracked_directories:
                    raise SelectionError(
                        "AFFECTED-SELECT-019", "checkout integrity validation failed"
                    )
                retained.append(directory)
            directories[:] = retained
    except (OSError, RuntimeError, ValueError) as error:
        raise SelectionError(
            "AFFECTED-SELECT-019", "checkout integrity validation failed"
        ) from error


def assert_clean_checkout(
    expected_head: str,
    *,
    event: str,
    runner_temp: Path,
    cache_mode: str,
    cache_role: str,
    root: Path = ROOT,
) -> BazelrcAuthority:
    """Require the governed invocation to run from the exact pristine event revision."""

    bazelrc_authority = assert_bazelrc_contract(
        event,
        runner_temp,
        cache_mode=cache_mode,
        cache_role=cache_role,
        root=root,
    )
    _assert_canonical_checkout_metadata(root)
    if git_revision("HEAD", root=root) != git_revision(expected_head, root=root):
        raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
    flags = run_git(["ls-files", "-v", "-z"], root=root)
    if flags.returncode:
        raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
    for entry in (field for field in flags.stdout.split(b"\0") if field):
        if len(entry) < 3 or entry[1:2] != b" ":
            raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
        tag = entry[:1]
        if tag == b"S" or b"a" <= tag <= b"z":
            raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
    comparisons: tuple[Sequence[str], ...] = (
        [
            "diff-index",
            "--cached",
            "--quiet",
            "--no-ext-diff",
            "--ignore-submodules=none",
            "HEAD",
            "--",
        ],
        ["diff-files", "--quiet", "--no-ext-diff", "--ignore-submodules=none", "--"],
    )
    for command in comparisons:
        result = run_git(command, root=root)
        if result.returncode or result.stdout:
            raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")

    tracked = _git_paths(["ls-files", "--cached", "-z"], root=root)
    untracked = _git_paths(["ls-files", "--others", "-z"], root=root)
    ignored = _git_paths(
        ["ls-files", "--others", "--ignored", "--exclude-standard", "-z"],
        root=root,
    )
    ignored_set = frozenset(ignored)
    if "user.bazelrc" in tracked:
        raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
    for relative in untracked:
        if relative not in ignored_set:
            raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
        if relative == "user.bazelrc" or _safe_bazel_output_symlink(relative, root=root):
            continue
        raise SelectionError("AFFECTED-SELECT-019", "checkout integrity validation failed")
    _assert_no_untracked_directories(tracked, root=root)
    return bazelrc_authority


def load_job_started_epoch(
    path: Path,
    *,
    runner_temp: Path | None = None,
    now_epoch: int | None = None,
) -> int:
    """Load an exact, non-future Unix-seconds timestamp without float coercion."""

    if runner_temp is not None and path != runner_temp / "bazel-job-started":
        raise SelectionError("AFFECTED-SELECT-014", "job-start timestamp is invalid")
    try:
        payload = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise SelectionError("AFFECTED-SELECT-014", "job-start timestamp is invalid") from error
    if payload.endswith("\n"):
        payload = payload[:-1]
    if (
        not payload
        or any(character < "0" or character > "9" for character in payload)
        or (len(payload) > 1 and payload.startswith("0"))
    ):
        raise SelectionError("AFFECTED-SELECT-014", "job-start timestamp is invalid")
    try:
        epoch = int(payload)
    except ValueError as error:
        raise SelectionError("AFFECTED-SELECT-014", "job-start timestamp is invalid") from error
    current = int(time.time()) if now_epoch is None else now_epoch
    if type(current) is not int or epoch <= 0 or current <= 0 or epoch > current:
        raise SelectionError("AFFECTED-SELECT-014", "job-start timestamp is invalid")
    return epoch


def assert_bazelrc_contract(
    event: str,
    runner_temp: Path,
    *,
    cache_mode: str,
    cache_role: str,
    root: Path = ROOT,
) -> BazelrcAuthority:
    """Accept only one exact, route-bound CI cache configuration."""

    expected_cache = runner_temp / "mindclade-bazel-disk-cache"
    if not runner_temp.is_absolute() or runner_temp.is_symlink():
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")

    path = root / "user.bazelrc"
    workspace_bazelrc = root / ".bazelrc"
    try:
        generated_authority, generated_payload = _read_authority_file(path)
        workspace_authority, workspace_payload = _read_authority_file(workspace_bazelrc)
        lines = tuple(generated_payload.decode("utf-8", errors="strict").splitlines())
        workspace_commands = tuple(
            tokens
            for raw_line in workspace_payload.decode("utf-8", errors="strict").splitlines()
            if (tokens := tuple(shlex.split(raw_line, comments=True, posix=True)))
        )
    except (OSError, UnicodeError, ValueError) as error:
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid") from error

    if (
        not workspace_commands
        or workspace_commands[-1] != WORKSPACE_BAZELRC_IMPORT
        or workspace_commands.count(WORKSPACE_BAZELRC_IMPORT) != 1
    ):
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")
    for command in workspace_commands[:-1]:
        if command[0] in {"import", "try-import", "startup"}:
            raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")
        for token in command[1:]:
            option_name = token.split("=", 1)[0].removeprefix("--").replace("-", "_")
            if option_name in {"nobuild", "no_build"} or option_name.startswith(
                (
                    "remote_",
                    "noremote_",
                    "no_remote_",
                    "experimental_remote_",
                    "noexperimental_remote_",
                    "no_experimental_remote_",
                    "disk_cache",
                    "experimental_disk_cache_",
                    "noexperimental_disk_cache_",
                    "no_experimental_disk_cache_",
                )
            ):
                raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")

    expected_role = CACHE_ROLE_BY_ROUTE.get((cache_mode, event))
    if expected_role is None or cache_role != expected_role:
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")
    expected_upload = "true" if cache_role == "writer" else "false"

    try:
        resolved_runner_temp = runner_temp.resolve(strict=True)
        resolved_root = root.resolve(strict=True)
        resolved_bazelrc = path.resolve(strict=True)
        resolved_workspace_bazelrc = workspace_bazelrc.resolve(strict=True)
    except (OSError, RuntimeError) as error:
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid") from error
    if (
        resolved_runner_temp != runner_temp
        or resolved_bazelrc != resolved_root / "user.bazelrc"
        or resolved_workspace_bazelrc != resolved_root / ".bazelrc"
    ):
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")

    if cache_mode == "disk":
        try:
            resolved_cache = expected_cache.resolve(strict=True)
        except (OSError, RuntimeError) as error:
            raise SelectionError(
                "AFFECTED-SELECT-020", "Bazel runtime contract is invalid"
            ) from error
        if (
            expected_cache.is_symlink()
            or resolved_cache != resolved_runner_temp / "mindclade-bazel-disk-cache"
            or resolved_cache.is_relative_to(resolved_root)
        ):
            raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")
        expected_lines = (
            BAZELRC_HEADER,
            f"build --disk_cache={expected_cache}",
            f"build --remote_upload_local_results={expected_upload}",
            *DISK_BAZELRC_FIXED_LINES,
        )
    else:
        expected_lines = (
            BAZELRC_HEADER,
            f"build --remote_cache={REMOTE_CACHE_ENDPOINT}",
            f"build --remote_upload_local_results={expected_upload}",
            *REMOTE_BAZELRC_FIXED_LINES,
        )
    if lines != expected_lines:
        raise SelectionError("AFFECTED-SELECT-020", "Bazel runtime contract is invalid")
    return BazelrcAuthority(
        root=resolved_root,
        workspace=workspace_authority,
        generated=generated_authority,
    )


def git_changed(base: str, *, root: Path = ROOT) -> tuple[Change, ...]:
    """Return an authoritative, rename-aware diff from ``base`` to ``HEAD``."""

    base_sha = git_revision(base, root=root)
    head_sha = git_revision("HEAD", root=root)
    ancestor = run_git(["merge-base", "--is-ancestor", base_sha, head_sha], root=root)
    if ancestor.returncode:
        raise SelectionError(
            "AFFECTED-SELECT-004", "base revision is not an ancestor of the selected head"
        )
    result = run_git(
        [
            "diff",
            "--no-ext-diff",
            "--no-textconv",
            "--name-status",
            "-z",
            "--find-renames",
            f"{base_sha}...{head_sha}",
        ],
        root=root,
    )
    if result.returncode:
        raise SelectionError("AFFECTED-SELECT-005", "Git changed-path inventory failed")

    fields = result.stdout.split(b"\0")
    if fields and fields[-1] == b"":
        fields.pop()
    changes: list[Change] = []
    index = 0
    try:
        while index < len(fields):
            status_text = fields[index].decode("utf-8", errors="strict")
            index += 1
            status = status_text[:1].upper()
            if status in {"C", "R"}:
                if index + 1 >= len(fields):
                    raise SelectionError(
                        "AFFECTED-SELECT-006", "Git changed-path inventory is malformed"
                    )
                old_path = fields[index].decode("utf-8", errors="strict")
                new_path = fields[index + 1].decode("utf-8", errors="strict")
                index += 2
                changes.append(Change(status=status, path=new_path, old_path=old_path))
            else:
                if index >= len(fields):
                    raise SelectionError(
                        "AFFECTED-SELECT-006", "Git changed-path inventory is malformed"
                    )
                path = fields[index].decode("utf-8", errors="strict")
                index += 1
                changes.append(Change(status=status, path=path))
    except UnicodeError as error:
        raise SelectionError(
            "AFFECTED-SELECT-006", "Git changed-path inventory is malformed"
        ) from error
    return _normalize_changes(changes)


def _global_reason(change: Change, contract: GlobalInputContract) -> str | None:
    if PurePosixPath(change.path).name in PACKAGE_BOUNDARY_FILES and change.status in {"A", "D"}:
        return "package_boundary_added" if change.status == "A" else "package_boundary_deleted"
    if change.status in STRUCTURAL_STATUSES:
        return f"structural_{change.status.lower()}"
    path = change.path
    if path in contract.exact_paths:
        return f"global_path:{path}"
    if path.endswith(".bzl"):
        return f"starlark:{path}"
    for prefix in contract.prefixes:
        if path.startswith(prefix):
            return f"global_prefix:{prefix}"
    return None


def _package_for(path: str, *, root: Path = ROOT) -> Path | None:
    candidate = root / path
    current = candidate if candidate.is_dir() else candidate.parent
    while True:
        if (current / "BUILD.bazel").is_file() or (current / "BUILD").is_file():
            return current
        if current == root:
            return None
        if root not in current.parents:
            return None
        current = current.parent


def _package_pattern(package: Path, *, root: Path = ROOT) -> str:
    relative = package.relative_to(root).as_posix()
    return "//:*" if relative == "." else f"//{relative}:*"


def _query_expression(seeds: Sequence[str], *, tests: bool) -> str:
    seed_set = "set(" + " ".join(json.dumps(seed) for seed in seeds) + ")"
    affected = f"rdeps(//..., {seed_set})"
    manual_pattern = json.dumps("manual")
    selected = "tests($affected)" if tests else 'kind(".* rule", $affected)'
    return (
        f"let affected = {affected} in "
        f'({selected} except attr("tags", {manual_pattern}, $affected))'
    )


def bazel_query(
    expression: str,
    *,
    root: Path = ROOT,
    bazel: Path | None = None,
) -> tuple[str, ...]:
    launcher = bazel or root / "tools/dev/bazelw"
    environment = os.environ.copy()
    for variable in SANITIZED_BUILD_ENVIRONMENT:
        environment.pop(variable, None)
    try:
        result = subprocess.run(
            [
                str(launcher),
                "--nohome_rc",
                "query",
                expression,
                "--config=ci",
                "--output=label",
                "--order_output=no",
            ],
            cwd=root,
            env=environment,
            text=True,
            capture_output=True,
            check=False,
        )
    except (OSError, UnicodeError) as error:
        raise SelectionError("AFFECTED-SELECT-007", "Bazel graph query failed") from error
    if result.returncode:
        raise SelectionError("AFFECTED-SELECT-007", "Bazel graph query failed")
    return tuple(sorted(set(line.strip() for line in result.stdout.splitlines() if line.strip())))


def select(
    changed: Iterable[Change | str],
    *,
    mode: str = "affected",
    base_sha: str | None = None,
    head_sha: str | None = None,
    event: str = "local",
    root: Path = ROOT,
    query: Query | None = None,
    global_inputs: GlobalInputContract | None = None,
) -> Selection:
    if mode not in {"affected", "full"}:
        raise SelectionError("AFFECTED-SELECT-001", "selection mode is unsupported")
    changes = _normalize_changes(changed)
    input_contract = global_inputs or load_global_input_contract()
    head = head_sha or git_revision("HEAD", root=root)
    if mode == "full":
        return Selection(
            mode="full",
            reason="explicit_full",
            changes=changes,
            seeds=(FULL_TARGET,),
            analysis_targets=(FULL_TARGET,),
            test_targets=(FULL_TARGET,),
            base_sha=base_sha,
            head_sha=head,
            event=event,
        )

    for change in changes:
        reason = _global_reason(change, input_contract)
        if reason is not None:
            return Selection(
                mode="full",
                reason=reason,
                changes=changes,
                seeds=(FULL_TARGET,),
                analysis_targets=(FULL_TARGET,),
                test_targets=(FULL_TARGET,),
                base_sha=base_sha,
                head_sha=head,
                event=event,
            )
        if not (root / change.path).exists():
            return Selection(
                mode="full",
                reason=f"missing_changed_path:{change.path}",
                changes=changes,
                seeds=(FULL_TARGET,),
                analysis_targets=(FULL_TARGET,),
                test_targets=(FULL_TARGET,),
                base_sha=base_sha,
                head_sha=head,
                event=event,
            )

    seeds: set[str] = set()
    for change in changes:
        package = _package_for(change.path, root=root)
        if package is None:
            return Selection(
                mode="full",
                reason=f"unowned_path:{change.path}",
                changes=changes,
                seeds=(FULL_TARGET,),
                analysis_targets=(FULL_TARGET,),
                test_targets=(FULL_TARGET,),
                base_sha=base_sha,
                head_sha=head,
                event=event,
            )
        seeds.add(_package_pattern(package, root=root))

    ordered_seeds = tuple(sorted(seeds))
    if not ordered_seeds:
        return Selection(
            mode="affected",
            reason="no_changed_paths",
            changes=changes,
            seeds=(),
            analysis_targets=(),
            test_targets=(),
            base_sha=base_sha,
            head_sha=head,
            event=event,
        )
    analysis_expression = _query_expression(ordered_seeds, tests=False)
    test_expression = _query_expression(ordered_seeds, tests=True)
    run_query = query or (lambda expression: bazel_query(expression, root=root))
    analysis_targets = tuple(sorted(set(run_query(analysis_expression))))
    test_targets = tuple(sorted(set(run_query(test_expression)) | {"//:gazelle_check"}))
    return Selection(
        mode="affected",
        reason="bazel_reverse_dependencies",
        changes=changes,
        seeds=ordered_seeds,
        analysis_targets=analysis_targets,
        test_targets=test_targets,
        base_sha=base_sha,
        head_sha=head,
        event=event,
        analysis_query=analysis_expression,
        test_query=test_expression,
    )


def _safe_evidence_dir(path: Path, *, root: Path = ROOT) -> Path:
    if path.exists() and path.is_symlink():
        raise SelectionError("AFFECTED-SELECT-008", "evidence directory is unsafe")
    resolved = path.resolve()
    try:
        resolved.relative_to(root.resolve())
    except ValueError:
        pass
    else:
        raise SelectionError("AFFECTED-SELECT-008", "evidence directory is unsafe")
    resolved.mkdir(parents=True, exist_ok=True)
    return resolved


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_targets(path: Path, targets: Sequence[str]) -> None:
    path.write_text("".join(f"{target}\n" for target in targets), encoding="utf-8")


def _append_step_summary(path: Path) -> None:
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary or not path.is_file():
        return
    with Path(summary).open("a", encoding="utf-8") as destination:
        destination.write(path.read_text(encoding="utf-8"))
        destination.write("\n")


def _compress(path: Path) -> None:
    if not path.is_file() or not path.stat().st_size:
        return
    compressed = path.with_name(path.name + ".gz")
    compressed.write_bytes(gzip.compress(path.read_bytes(), compresslevel=9, mtime=0))
    path.unlink()


def _run_phase(
    phase: str,
    targets: Sequence[str],
    *,
    evidence_dir: Path,
    bazelrc_authority: BazelrcAuthority | None = None,
    root: Path = ROOT,
) -> dict[str, Any]:
    started_at = utc_now()
    started = time.monotonic()
    if not targets:
        return {
            "phase": phase,
            "status": "skipped",
            "exit_code": 0,
            "reason": "no_targets",
            "started_at": started_at,
            "elapsed_seconds": 0.0,
        }

    target_file = evidence_dir / f"{phase}.targets"
    bep = evidence_dir / f"{phase}.bep.json"
    profile = evidence_dir / f"{phase}.profile.json.gz"
    _write_targets(target_file, targets)
    verb = "build" if phase == "analysis" else "test"
    command = [
        str(root / "tools/dev/bazelw"),
        "--nohome_rc",
        verb,
        "--config=ci",
        "--skip_incompatible_explicit_targets",
        f"--target_pattern_file={target_file}",
        f"--build_event_json_file={bep}",
        f"--profile={profile}",
    ]
    if phase == "analysis":
        command.insert(3, "--nobuild")
    environment = os.environ.copy()
    for variable in SANITIZED_BUILD_ENVIRONMENT:
        environment.pop(variable, None)
    if bazelrc_authority is not None:
        bazelrc_authority.assert_unchanged(root=root)
    result = subprocess.run(command, cwd=root, env=environment, check=False)

    summary_status = 0
    if bep.is_file() and bep.stat().st_size:
        summary_json = evidence_dir / f"{phase}.summary.json"
        summary_markdown = evidence_dir / f"{phase}.summary.md"
        summary = subprocess.run(
            [
                sys.executable,
                str(root / "tools/analysis/summarize_bazel_bep.py"),
                "--bep",
                str(bep),
                "--label",
                "configured analysis" if phase == "analysis" else "Bazel test",
                "--json-output",
                str(summary_json),
                "--markdown-output",
                str(summary_markdown),
            ],
            cwd=root,
            check=False,
        )
        summary_status = summary.returncode
        _append_step_summary(summary_markdown)
        _compress(bep)

    exit_code = result.returncode or summary_status
    return {
        "phase": phase,
        "status": "passed" if exit_code == 0 else "failed",
        "exit_code": exit_code,
        "bazel_exit_code": result.returncode,
        "summary_exit_code": summary_status,
        "started_at": started_at,
        "elapsed_seconds": round(time.monotonic() - started, 3),
        "target_count": len(targets),
        "command": command,
    }


def write_failure_evidence(
    evidence_dir: Path,
    *,
    mode: str,
    event: str,
    base_sha: str | None,
    error: Exception,
    root: Path = ROOT,
) -> None:
    try:
        directory = _safe_evidence_dir(evidence_dir, root=root)
        if isinstance(error, ContractError):
            error_code = error.code
            error_message = error.public_message
        else:
            error_code = "AFFECTED-SELECT-999"
            error_message = "affected selection failed"
        _write_json(
            directory / "selection.json",
            {
                "schema_version": SCHEMA_VERSION,
                "base_sha": base_sha,
                "event": event,
                "mode": mode,
                "reason": "selection_failed",
                "error": {"code": error_code, "message": error_message},
            },
        )
    except (OSError, UnicodeError, SelectionError):
        return


def _execute_selection(
    selection: Selection,
    evidence_dir: Path,
    *,
    bazelrc_authority: BazelrcAuthority | None = None,
    job_started_epoch: int | None = None,
    root: Path = ROOT,
) -> int:
    directory = _safe_evidence_dir(evidence_dir, root=root)
    payload = selection.as_dict()
    _write_json(directory / "selection.json", payload)

    execution: list[dict[str, Any]] = []
    analysis = _run_phase(
        "analysis",
        selection.analysis_targets,
        evidence_dir=directory,
        bazelrc_authority=bazelrc_authority,
        root=root,
    )
    execution.append(analysis)
    if analysis["exit_code"] == 0:
        execution.append(
            _run_phase(
                "test",
                selection.test_targets,
                evidence_dir=directory,
                bazelrc_authority=bazelrc_authority,
                root=root,
            )
        )
    else:
        execution.append(
            {
                "phase": "test",
                "status": "skipped",
                "exit_code": analysis["exit_code"],
                "reason": "analysis_failed",
                "started_at": utc_now(),
                "elapsed_seconds": 0.0,
            }
        )

    total_elapsed = None
    if job_started_epoch is not None:
        total_elapsed = round(max(0.0, time.time() - job_started_epoch), 3)
    payload["execution"] = execution
    payload["completed_at"] = utc_now()
    payload["job_elapsed_seconds"] = total_elapsed
    payload["latency_slo_seconds"] = LATENCY_SLO_SECONDS
    payload["latency_slo_met"] = (
        None
        if total_elapsed is None or selection.mode != "affected"
        else total_elapsed <= LATENCY_SLO_SECONDS
    )
    _write_json(directory / "selection.json", payload)
    _write_json(
        directory / "run-metrics.json",
        {
            "schema_version": SCHEMA_VERSION,
            "event": selection.event,
            "mode": selection.mode,
            "reason": selection.reason,
            "head_sha": selection.head_sha,
            "completed_at": payload["completed_at"],
            "job_elapsed_seconds": total_elapsed,
            "latency_slo_seconds": LATENCY_SLO_SECONDS,
            "latency_slo_met": payload["latency_slo_met"],
            "analysis_target_count": len(selection.analysis_targets),
            "test_target_count": len(selection.test_targets),
            "shard_index": (
                selection.partition["selected_shard"]["index"]
                if selection.partition is not None
                else None
            ),
            "shard_count": (
                selection.partition["shard_count"] if selection.partition is not None else None
            ),
            "analysis_graph_sha256": (
                selection.partition["analysis_graph_sha256"]
                if selection.partition is not None
                else None
            ),
            "test_graph_sha256": (
                selection.partition["test_graph_sha256"]
                if selection.partition is not None
                else None
            ),
        },
    )
    return next((item["exit_code"] for item in execution if item["exit_code"]), 0)


def execute_selection(
    selection: Selection,
    evidence_dir: Path,
    *,
    bazelrc_authority: BazelrcAuthority | None = None,
    job_started_epoch: int | None = None,
    root: Path = ROOT,
) -> int:
    """Execute a selection behind a stable, redacted infrastructure-error boundary."""

    try:
        return _execute_selection(
            selection,
            evidence_dir,
            bazelrc_authority=bazelrc_authority,
            job_started_epoch=job_started_epoch,
            root=root,
        )
    except SelectionError:
        raise
    except (OSError, UnicodeError, subprocess.SubprocessError) as error:
        raise SelectionError("AFFECTED-SELECT-021", "Bazel execution failed") from error


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="*")
    parser.add_argument("--base")
    parser.add_argument("--mode", choices=("affected", "full"), default="affected")
    parser.add_argument("--event", default=os.environ.get("GITHUB_EVENT_NAME", "local"))
    parser.add_argument("--format", choices=("lines", "json"), default="lines")
    parser.add_argument("--kind", choices=("analysis", "test"), default="test")
    args = parser.parse_args()
    if args.mode == "affected" and not args.paths and not args.base:
        parser.error("affected mode requires paths or --base")
    changes = (
        tuple(Change(status="M", path=path) for path in args.paths)
        if args.paths
        else git_changed(args.base)
        if args.mode == "affected"
        else ()
    )
    base_sha = git_revision(args.base) if args.base else None
    selection = select(changes, mode=args.mode, base_sha=base_sha, event=args.event)
    if args.format == "json":
        print(json.dumps(selection.as_dict(), indent=2, sort_keys=True))
    else:
        targets = selection.analysis_targets if args.kind == "analysis" else selection.test_targets
        print("\n".join(targets))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
