# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

package(default_visibility = ["//visibility:private"])

filegroup(
    name = "docs",
    srcs = [
        "GO_FOUNDATION_CONSUMPTION.md",
        "PRODUCTION_READINESS.md",
        "README.md",
    ],
    visibility = ["//visibility:public"],
)
