# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "blobtest",
    testonly = True,
    srcs = [
        "doc.go",
        "suite.go",
    ],
    importpath = "go.mindclade.dev/libs/go/storage/blob/blobtest",
    deps = [
        "//libs/go/faults",
        "//libs/go/identifiers",
        "//libs/go/storage/blob",
    ],
)
