# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "fused",
    srcs = [
        "__init__.py",
        "fused.py",
    ],
    imports = ["../../../.."],
    deps = ["//kernels/ops/fused"],
)
