# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

exports_files(["README.md"])

go_library(
    name = "inbox",
    srcs = [
        "doc.go",
        "errors.go",
        "processor.go",
        "runner.go",
    ],
    importpath = "go.mindclade.dev/libs/go/coordination/inbox",
    deps = [
        "//libs/go/faults",
        "//libs/go/idempotency",
        "//libs/go/identifiers",
        "//libs/go/requestmeta",
        "//libs/go/storage/sql/transaction",
    ],
)

go_test(
    name = "inbox_test",
    srcs = ["processor_test.go"],
    deps = [
        ":inbox",
        "//libs/go/idempotency",
        "//libs/go/idempotency/idempotencytest",
        "//libs/go/identifiers",
    ],
)
