# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "otel",
    srcs = [
        "doc.go",
        "otel.go",
    ],
    importpath = "go.mindclade.dev/libs/go/connectx/otel",
    deps = [
        "//libs/go/faults",
        "@com_connectrpc_connect//:connect",
        "@com_connectrpc_otelconnect//:otelconnect",
    ],
)

go_test(
    name = "otel_test",
    srcs = ["otel_test.go"],
    embed = [":otel"],
)
