# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//tools/build:pytest.bzl", "pytest_test")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "run_lib",
    srcs = ["run.py"],
    data = [
        "h100-job.json",
        "h200-job.json",
    ],
    imports = ["../../.."],
)

py_binary(
    name = "run",
    srcs = ["run.py"],
    data = [
        "h100-job.json",
        "h200-job.json",
    ],
    visibility = ["//visibility:public"],
)

pytest_test(
    name = "test_run",
    srcs = ["tests/test_run.py"],
    data = [
        "h100-job.json",
        "h200-job.json",
    ],
    imports = ["../../.."],
    deps = [":run_lib"],
)
