# Copyright 2026 Mindclade. All rights reserved.
# Confidential and proprietary.

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "identifiers",
    srcs = [
        "digest.go",
        "doc.go",
        "errors.go",
        "generator.go",
        "id.go",
        "kind.go",
        "uuid.go",
    ],
    importpath = "mindclade.internal/libs/go/identifiers",
)

go_test(
    name = "identifiers_test",
    srcs = [
        "api_test.go",
        "digest_test.go",
        "errors_test.go",
        "generator_test.go",
        "id_test.go",
        "kind_test.go",
        "uuid_test.go",
    ],
    embed = [":identifiers"],
)
