# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("//tools/build:pytest.bzl", "pytest_test")

pytest_test(
    name = "test_safety",
    srcs = ["test_safety.py"],
    imports = ["../../.."],
    deps = ["//serving/safety"],
)
