# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "pdb",
    srcs = glob(["*.go"], exclude = ["*_test.go"]),
    importpath = "go.mindclade.dev/data/connectors/pdb",
    deps = ["//data/connectors"],
)

go_test(
    name = "pdb_test",
    srcs = ["pdb_test.go"],
    embed = [":pdb"],
    deps = ["//data/connectors"],
)
