# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "redis",
    srcs = [
        "doc.go",
        "options.go",
        "scripts.go",
        "store.go",
    ],
    importpath = "go.mindclade.dev/libs/go/storage/cache/redis",
    deps = [
        "//libs/go/faults",
        "//libs/go/storage/cache",
        "@com_github_redis_go_redis_v9//:redis",
    ],
)

go_test(
    name = "redis_test",
    srcs = [
        "options_test.go",
        "store_test.go",
    ],
    embed = [":redis"],
    deps = [
        "//libs/go/faults",
        "//libs/go/storage/cache",
        "@com_github_redis_go_redis_v9//:redis",
    ],
)
