# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "huggingface",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    importpath = "go.mindclade.dev/data/connectors/huggingface",
    deps = ["//data/connectors"],
)

go_test(
    name = "huggingface_test",
    srcs = ["huggingface_test.go"],
    embed = [":huggingface"],
    deps = ["//data/connectors"],
)
