# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:private"])

go_library(
    name = "vanity",
    srcs = ["vanity.go"],
    importpath = "go.mindclade.dev/services/go_vanity/internal/vanity",
    visibility = ["//services/go_vanity:__subpackages__"],
)

go_test(
    name = "vanity_test",
    srcs = ["vanity_test.go"],
    embed = [":vanity"],
)
