# Copyright 2026 Mindclade. All rights reserved.
# Confidential, proprietary, and trade-secret information.

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:private"])

go_library(
    name = "vanity",
    srcs = ["vanity.go"],
    importpath = "mindclade.internal/services/go_vanity/internal/vanity",
    visibility = ["//services/go_vanity:__subpackages__"],
)

go_test(
    name = "vanity_test",
    srcs = ["vanity_test.go"],
    embed = [":vanity"],
)
