# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = [
    "//control:__subpackages__",
    "//services:__subpackages__",
])

go_library(
    name = "pubsub",
    srcs = [
        "attributes.go",
        "config.go",
        "doc.go",
        "provider.go",
        "publisher.go",
        "subscription.go",
    ],
    importpath = "go.mindclade.dev/libs/go/messaging/pubsub",
    deps = [
        "//libs/go/faults",
        "//libs/go/identifiers",
        "//libs/go/messaging",
        "//libs/go/requestmeta",
    ],
)

go_test(
    name = "pubsub_test",
    srcs = ["pubsub_test.go"],
    embed = [":pubsub"],
    deps = [
        "//libs/go/identifiers",
        "//libs/go/messaging",
        "//libs/go/requestmeta",
    ],
)
