---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policies.yaml
  - resource-quotas.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
