# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "memory",
    srcs = [
        "doc.go",
        "store.go",
    ],
    importpath = "go.mindclade.dev/libs/go/storage/lease/memory",
    deps = [
        "//libs/go/clock",
        "//libs/go/faults",
        "//libs/go/storage/lease",
    ],
)

go_test(
    name = "memory_test",
    srcs = [
        "conformance_test.go",
        "store_test.go",
    ],
    embed = [":memory"],
    deps = [
        "//libs/go/clock",
        "//libs/go/faults",
        "//libs/go/storage/lease",
        "//libs/go/storage/lease/leasetest",
    ],
)
