# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "reference_database_proto",
    srcs = ["reference_database.proto"],
    strip_import_prefix = "/protocols/proto",
    deps = ["//protocols/proto/mindclade/common/v1:artifact_ref_proto"],
)

proto_library(
    name = "model_bundle_proto",
    srcs = ["model_bundle.proto"],
    strip_import_prefix = "/protocols/proto",
    deps = [
        "//protocols/proto/mindclade/common/v1:identifiers_proto",
        "@protobuf//:timestamp_proto",
    ],
)

proto_library(
    name = "model_service_proto",
    srcs = ["service.proto"],
    strip_import_prefix = "/protocols/proto",
    deps = [
        ":model_bundle_proto",
        "//protocols/proto/mindclade/common/v1:identifiers_proto",
        "//protocols/proto/mindclade/common/v1:pagination_proto",
    ],
)

proto_library(
    name = "release_proto",
    srcs = ["release.proto"],
    strip_import_prefix = "/protocols/proto",
    deps = ["//protocols/proto/mindclade/common/v1:artifact_ref_proto"],
)

filegroup(
    name = "scaffold_files",
    srcs = glob(
        ["*.proto"],
        exclude = [
            "reference_database.proto",
            "release.proto",
            "model_bundle.proto",
            "service.proto",
        ],
    ),
    visibility = ["//visibility:public"],
)
