#!/usr/bin/env python3
# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

"""Verify that the committed Cargo lock is a Cargo-generated, non-empty closure."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOCK = ROOT / "Cargo.lock"


def main() -> int:
    if not LOCK.exists() or LOCK.stat().st_size < 128:
        print("Cargo.lock is missing or incomplete; run the pinned Rust qualification lane")
        return 1
    text = LOCK.read_text(errors="replace")
    if "# This file is automatically @generated by Cargo." not in text or "[[package]]" not in text:
        print("Cargo.lock is not a Cargo-generated dependency closure")
        return 1
    cargo = shutil.which("cargo")
    if cargo:
        result = subprocess.run(
            [cargo, "metadata", "--locked", "--format-version", "1", "--no-deps"],
            cwd=ROOT,
            check=False,
        )
        if result.returncode:
            return result.returncode
    print("Cargo.lock policy passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
