# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary
#

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "mlflow_exporter",
    srcs = [
        "exporters/__init__.py",
        "exporters/mlflow.py",
        "exporters/mlflow_tracing.py",
    ],
    imports = ["../../.."],
)

filegroup(
    name = "remaining_scaffold_files",
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD.bazel",
            "exporters/__init__.py",
            "exporters/mlflow.py",
            "exporters/mlflow_tracing.py",
            "tests/**",
        ],
    ),
)
