# Copyright © 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

{{- if and .Values.activation.enabled .Values.monitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "mindclade-mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mindclade-mlflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mindclade-mlflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metadata-lineage
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      timeout: {{ .Values.monitoring.timeout }}
{{- end }}
